import React, { createContext, useContext, useState, useEffect, type ReactNode } from 'react';

export type Language = 'en' | 'zh' | 'es' | 'ja' | 'fr';

interface LanguageContextType {
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translation dictionaries
const translations: Record<Language, Record<string, string>> = {
    en: {
        // Navigation
        'nav.home': 'Home',
        'nav.calculators': 'Calculators',
        'nav.categories': 'Categories',
        'nav.about': 'About',
        'nav.contact': 'Contact',
        'nav.allTools': 'All Tools',
        'nav.search': 'Search calculators...',
        
        // Hero
        'hero.badge': 'New Tools Added',
        'hero.title1': 'Smart calculators for your',
        'hero.title2': 'financial future.',
        'hero.subtitle': 'Make better decisions with our free, accurate, and easy-to-use tools. From salary taxes to investment growth, we\'ve got you covered.',
        'hero.searchPlaceholder': 'Search calculators... e.g. mortgage, tax, interest',
        'hero.trending': 'Trending:',
        
        // Popular Tools
        'popular.title': 'Popular Calculators',
        'popular.subtitle': 'Most used tools by our community',
        
        // Categories Section
        'categories.title': 'Browse by Category',
        'categories.subtitle': 'Find the right calculator for your needs',
        'categories.viewAll': 'View All',
        
        // Category Names
        'cat.finance': 'Finance',
        'cat.business': 'Business',
        'cat.loansDebt': 'Loans & Debt',
        'cat.investment': 'Investment',
        'cat.health': 'Health',
        'cat.math': 'Math',
        'cat.geometry': 'Geometry',
        'cat.conversion': 'Conversion',
        'cat.everydayLife': 'Everyday Life',
        'cat.biology': 'Biology',
        'cat.chemistry': 'Chemistry',
        'cat.physics': 'Physics',
        'cat.sports': 'Sports',
        'cat.statistics': 'Statistics',
        'cat.other': 'Other',
        
        // Category Descriptions
        'cat.finance.desc': 'Salary, tax, investments, and retirement planning.',
        'cat.business.desc': 'ROI, margin, break-even, and business calculators.',
        'cat.loansDebt.desc': 'Mortgage, auto loans, and amortization calculators.',
        'cat.investment.desc': 'Compound interest, 401k, and inflation calculators.',
        'cat.health.desc': 'BMI, BMR, pregnancy, and fitness trackers.',
        'cat.math.desc': 'Algebra, geometry, statistics, and matrices.',
        'cat.geometry.desc': 'Calculate areas, volumes, and construction needs.',
        'cat.conversion.desc': 'Convert length, weight, volume, temperature, and more.',
        'cat.everydayLife.desc': 'Time, date, shopping, and daily utilities.',
        'cat.biology.desc': 'Genetics, cell biology, and evolution calculators.',
        'cat.chemistry.desc': 'Molarity, pH, periodic table, and reactions.',
        'cat.physics.desc': 'Mechanics, thermodynamics, electricity, and waves.',
        'cat.sports.desc': 'Running pace, cycling power, and scoreboards.',
        'cat.statistics.desc': 'Probability, distributions, and data analysis.',
        'cat.other.desc': 'Miscellaneous tools and fun calculators.',
        
        // Tool Names
        'tool.salaryCalculator': 'Salary Calculator',
        'tool.mortgageCalc': 'Mortgage Calc',
        'tool.investmentReturn': 'Investment Return',
        'tool.roiCalculator': 'ROI Calculator',
        'tool.marginCalc': 'Margin Calc',
        'tool.breakEven': 'Break-Even',
        'tool.autoLoan': 'Auto Loan',
        'tool.amortization': 'Amortization',
        'tool.compoundInterest': 'Compound Interest',
        'tool.401kCalc': '401k Calc',
        'tool.inflation': 'Inflation',
        'tool.bmiCalculator': 'BMI Calculator',
        'tool.calorieCalc': 'Calorie Calc',
        'tool.dueDate': 'Due Date',
        'tool.percentageCalc': 'Percentage Calc',
        'tool.binaryCalc': 'Binary Calc',
        'tool.primeNumbers': 'Prime Numbers',
        'tool.circleCalc': 'Circle Calc',
        'tool.triangleCalc': 'Triangle Calc',
        'tool.paintCalculator': 'Paint Calculator',
        'tool.lengthConverter': 'Length Converter',
        'tool.weightConverter': 'Weight Converter',
        'tool.currency': 'Currency',
        'tool.ageCalculator': 'Age Calculator',
        'tool.dateDifference': 'Date Difference',
        'tool.tipCalculator': 'Tip Calculator',
        'tool.dnaReplication': 'DNA Replication',
        'tool.alleleFrequency': 'Allele Frequency',
        'tool.molarityCalc': 'Molarity Calc',
        'tool.phCalculator': 'pH Calculator',
        'tool.velocityCalculator': 'Velocity Calculator',
        'tool.paceCalculator': 'Pace Calculator',
        'tool.standardDeviation': 'Standard Deviation',
        'tool.randomNumberGenerator': 'Random Number Generator',
        
        // Popular Tools Names & Descriptions
        'popular.paycheck': 'Paycheck Calculator',
        'popular.paycheck.desc': 'Calculate your take-home pay after taxes for any pay period.',
        'popular.mortgage': 'Mortgage Calculator',
        'popular.mortgage.desc': 'Calculate monthly mortgage payments with taxes and insurance.',
        'popular.bmi': 'BMI Calculator',
        'popular.bmi.desc': 'Calculate your Body Mass Index based on height and weight.',
        'popular.tip': 'Tip Calculator',
        'popular.tip.desc': 'Calculate tip amount and split the bill among friends.',
        'popular.gpa': 'GPA Calculator',
        'popular.gpa.desc': 'Calculate your Grade Point Average instantly.',
        'popular.age': 'Age Calculator',
        'popular.age.desc': 'Calculate exact age in years, months, and days.',
        'popular.sleep': 'Sleep Calculator',
        'popular.sleep.desc': 'Find the best time to wake up based on sleep cycles.',
        'popular.password': 'Password Generator',
        'popular.password.desc': 'Create strong, secure passwords instantly.',
        'popular.compound': 'Compound Interest',
        'popular.compound.desc': 'See how your investments grow over time.',
        'popular.bodyFat': 'Body Fat Calculator',
        'popular.bodyFat.desc': 'Estimate your body fat percentage with the Navy method.',
        'popular.homeAfford': 'Home Affordability',
        'popular.homeAfford.desc': 'How much house can you afford based on income?',
        'popular.studentLoan': 'Student Loan Calculator',
        'popular.studentLoan.desc': 'Plan your student loan repayment strategy.',
        
        // Popular Tool Categories
        'popular.cat.salary': 'Salary',
        'popular.cat.loans': 'Loans',
        'popular.cat.health': 'Health',
        'popular.cat.everyday': 'Everyday',
        'popular.cat.education': 'Education',
        'popular.cat.tools': 'Tools',
        'popular.cat.security': 'Security',
        'popular.cat.investment': 'Investment',
        'popular.cat.fitness': 'Fitness',
        'popular.cat.finance': 'Finance',
        
        // Calculator Page
        'calc.calculate': 'Calculate',
        'calc.reset': 'Reset',
        'calc.result': 'Result',
        'calc.howItWorks': 'How It Works',
        'calc.formula': 'Formula',
        'calc.faq': 'FAQ',
        
        // Footer
        'footer.disclaimer': 'This website does not provide tax, legal, or investment advice. All calculations are estimates and should be used for informational purposes only.',
        'footer.copyright': 'All rights reserved.',
        'footer.calculators': 'Calculators',
        'footer.company': 'Company',
        'footer.salaryTax': 'Salary & Tax',
        'footer.loansDebt': 'Loans & Debt',
        'footer.investment': 'Investment',
        'footer.aboutUs': 'About Us',
        'footer.privacy': 'Privacy Policy',
        'footer.terms': 'Terms of Service',
        
        // Tags
        'tag.tax': 'Tax',
        'tag.mortgage': 'Mortgage',
        'tag.loan': 'Loan',
        'tag.debt': 'Debt',
        'tag.bmi': 'BMI',
        'tag.calorie': 'Calorie',
        'tag.percentage': 'Percentage',
        'tag.binary': 'Binary',
        'tag.circle': 'Circle',
        'tag.triangle': 'Triangle',
        
        // About Page
        'about.title': 'About WorkMoney Tools',
        'about.subtitle': 'We provide free, accurate, and easy-to-use online calculators to help you make better financial decisions and solve everyday problems.',
        'about.mission': 'Our Mission',
        'about.missionText': 'Our mission is to democratize access to financial and mathematical tools. We believe everyone should have access to accurate calculators without needing expensive software or professional services.',
        'about.whyChoose': 'Why Choose Us?',
        'about.fast': 'Fast & Accurate',
        'about.fastDesc': 'Our calculators use proven formulas and algorithms to deliver instant, accurate results.',
        'about.userFriendly': 'User-Friendly',
        'about.userFriendlyDesc': 'Clean, intuitive interfaces that make complex calculations simple and accessible.',
        'about.privacy': 'Privacy First',
        'about.privacyDesc': 'All calculations happen in your browser. We never store your personal data.',
        'about.calculators': 'Calculators',
        'about.categories': 'Categories',
        'about.free': 'Free',
        'about.dataCollected': 'Data Collected',
        'about.disclaimer': 'Disclaimer',
        'about.disclaimerText': 'The calculators provided on this website are for informational purposes only. They are not intended to provide tax, legal, financial, or investment advice.',
        
        // All Tools Page
        'allTools.title': 'All Calculators',
        'allTools.subtitle': 'Browse our complete collection of free calculators',
        'allTools.searchPlaceholder': 'Search calculators...',
        'allTools.allCategories': 'All Categories',
        'allTools.showing': 'Showing',
        'allTools.calculator': 'calculator',
        'allTools.calculators': 'calculators',
        'allTools.in': 'in',
        'allTools.matching': 'matching',
        'allTools.noFound': 'No calculators found',
        'allTools.tryAdjusting': 'Try adjusting your search or filter criteria',
        'allTools.clearFilters': 'Clear Filters',
        'allTools.browseByCategory': 'Browse by Category',
        'allTools.tools': 'tools',
        
        // Contact Page
        'contact.title': 'Contact Us',
        'contact.subtitle': 'Have a question, suggestion, or found a bug? We\'d love to hear from you!',
        'contact.feedback': 'Feedback',
        'contact.feedbackDesc': 'Help us improve! Share your ideas for new calculators or features.',
        'contact.email': 'Email',
        'contact.yourName': 'Your Name',
        'contact.emailAddress': 'Email Address',
        'contact.subject': 'Subject',
        'contact.selectSubject': 'Select a subject',
        'contact.generalFeedback': 'General Feedback',
        'contact.reportBug': 'Report a Bug',
        'contact.featureRequest': 'Feature Request',
        'contact.question': 'Question',
        'contact.other': 'Other',
        'contact.message': 'Message',
        'contact.messagePlaceholder': 'Tell us what\'s on your mind...',
        'contact.sendMessage': 'Send Message',
        'contact.messageSent': 'Message Sent!',
        'contact.thankYou': 'Thank you for reaching out. We\'ll get back to you as soon as possible.',
        'contact.sendAnother': 'Send Another Message',
        
        // 404 Page
        'notFound.title': 'Page Not Found',
        'notFound.message': 'Oops! The page you\'re looking for doesn\'t exist or has been moved. Let\'s get you back on track.',
        'notFound.goHome': 'Go Home',
        'notFound.browseCalc': 'Browse Calculators',
        'notFound.popularCalc': 'Popular Calculators',
        
        // Breadcrumbs
        'breadcrumb.home': 'Home',
        
        // Related Categories
        'related.title': 'Related Categories',
        
        // Common
        'common.loading': 'Loading...',
        'common.error': 'Error',
        'common.noResults': 'No results found',
        'common.readMore': 'Read More',
        'common.showLess': 'Show Less',
        
        // SEO Meta
        'seo.home.title': '80+ Free Online Calculators - Finance, Health, Math & More',
        'seo.home.description': 'Access 80+ free, accurate online calculators for paycheck, mortgage, BMI, tip, GPA, student loans, and more. Smart tools trusted by millions for daily financial and mathematical needs.',
        'seo.home.keywords': 'online calculator, free calculator, paycheck calculator, mortgage calculator, bmi calculator, tip calculator, gpa calculator, student loan calculator, finance tools',
        
        // Privacy Page
        'privacy.title': 'Privacy Policy',
        'privacy.lastUpdated': 'Last updated: December 2024',
        'privacy.summary': 'We respect your privacy. All calculations happen in your browser - we don\'t store your personal data. We use analytics to improve our service and may show ads to keep our tools free.',
        'privacy.infoCollect': 'Information We Collect',
        'privacy.calcData': 'Calculator Data',
        'privacy.calcDataDesc': 'All calculations are performed locally in your browser. We do not collect, store, or transmit any of the numbers or information you enter into our calculators.',
        'privacy.analyticsData': 'Analytics Data',
        'privacy.analyticsDataDesc': 'We use Vercel Analytics to collect anonymous usage data such as:',
        'privacy.pagesVisited': 'Pages visited',
        'privacy.browserType': 'Browser type and version',
        'privacy.deviceType': 'Device type (mobile/desktop)',
        'privacy.geoLocation': 'General geographic location (country level)',
        'privacy.howUse': 'How We Use Information',
        'privacy.howUseDesc': 'We use analytics data to:',
        'privacy.improveCalc': 'Improve our calculators and user experience',
        'privacy.popularTools': 'Understand which tools are most popular',
        'privacy.fixIssues': 'Identify and fix technical issues',
        'privacy.newFeatures': 'Make informed decisions about new features',
        'privacy.cookies': 'Cookies and Tracking',
        'privacy.cookiesDesc1': 'We use minimal cookies necessary for the website to function. Third-party services like Google AdSense may use cookies to serve relevant advertisements.',
        'privacy.cookiesDesc2': 'You can control cookie preferences through your browser settings.',
        'privacy.thirdParty': 'Third-Party Services',
        'privacy.thirdPartyDesc': 'We use the following third-party services:',
        'privacy.vercel': 'Vercel',
        'privacy.vercelDesc': 'Website hosting and analytics',
        'privacy.adsense': 'Google AdSense',
        'privacy.adsenseDesc': 'Advertising (helps keep our tools free)',
        'privacy.thirdPartyNote': 'These services have their own privacy policies governing their data practices.',
        'privacy.dataSecurity': 'Data Security',
        'privacy.dataSecurityDesc': 'Since we don\'t collect personal calculator data, there\'s nothing to secure on our end. Your calculations stay in your browser and are never transmitted to our servers.',
        'privacy.yourRights': 'Your Rights',
        'privacy.yourRightsDesc': 'You have the right to opt out of analytics tracking by using browser extensions like ad blockers or "Do Not Track" settings. Since we don\'t collect personal data, there\'s no personal information to access, modify, or delete.',
        'privacy.childrenPrivacy': 'Children\'s Privacy',
        'privacy.childrenPrivacyDesc': 'Our website is intended for general audiences and does not knowingly collect information from children under 13.',
        'privacy.changes': 'Changes to This Policy',
        'privacy.changesDesc': 'We may update this privacy policy from time to time. We will notify users of any material changes by updating the "Last updated" date at the top of this page.',
        'privacy.contact': 'Contact Us',
        'privacy.contactDesc': 'If you have questions about this privacy policy, please contact us at',
        
        // Terms Page
        'terms.title': 'Terms of Service',
        'terms.lastUpdated': 'Last updated: December 2024',
        'terms.important': 'By using WorkMoney Tools, you agree to these terms. Our calculators are for informational purposes only and should not be considered professional financial, tax, legal, or medical advice.',
        'terms.acceptance': 'Acceptance of Terms',
        'terms.acceptanceDesc': 'By accessing and using WorkMoney Tools ("the Service"), you accept and agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use our website.',
        'terms.description': 'Description of Service',
        'terms.descriptionText': 'WorkMoney Tools provides free online calculators for financial, mathematical, health, and other calculations. These tools are designed to help users make estimates and understand concepts, but should not be relied upon for making important decisions without professional consultation.',
        'terms.disclaimer': 'Disclaimer of Warranties',
        'terms.disclaimerText1': 'THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED.',
        'terms.disclaimerText2': 'We do not warrant that:',
        'terms.errorFree': 'The calculators will be error-free or produce accurate results in all circumstances',
        'terms.uninterrupted': 'The service will be uninterrupted or available at all times',
        'terms.suitability': 'Any results from using our calculators are suitable for any specific purpose',
        'terms.notAdvice': 'Not Professional Advice',
        'terms.notAdviceText': 'The calculators and information provided on this website are for educational and informational purposes only. They are NOT substitutes for:',
        'terms.taxAdvice': 'Professional tax advice from a qualified accountant or tax advisor',
        'terms.legalAdvice': 'Legal advice from a licensed attorney',
        'terms.financialAdvice': 'Financial advice from a certified financial planner',
        'terms.medicalAdvice': 'Medical advice from a qualified healthcare provider',
        'terms.otherAdvice': 'Any other professional advice',
        'terms.consultPro': 'Always consult with qualified professionals before making important decisions based on calculations from our tools.',
        'terms.liability': 'Limitation of Liability',
        'terms.liabilityText': 'TO THE MAXIMUM EXTENT PERMITTED BY LAW, WORKMONEY TOOLS SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, OR ANY LOSS OF PROFITS OR REVENUES, WHETHER INCURRED DIRECTLY OR INDIRECTLY, OR ANY LOSS OF DATA, USE, GOODWILL, OR OTHER INTANGIBLE LOSSES RESULTING FROM YOUR USE OF THE SERVICE.',
        'terms.accuracy': 'Accuracy of Information',
        'terms.accuracyText': 'While we strive to provide accurate calculations and up-to-date information, we make no guarantees about the accuracy, completeness, or timeliness of any information or calculations. Tax rates, interest rates, and other data may change. Users are responsible for verifying any information before relying on it.',
        'terms.userResp': 'User Responsibilities',
        'terms.userRespText': 'By using our service, you agree to:',
        'terms.lawfulUse': 'Use the calculators only for lawful purposes',
        'terms.noDisrupt': 'Not attempt to disrupt or damage the service',
        'terms.noAutomation': 'Not use automated systems to access the service in a manner that sends more requests than a human could reasonably produce',
        'terms.verify': 'Verify important calculations with other sources or professionals',
        'terms.ip': 'Intellectual Property',
        'terms.ipText': 'All content on WorkMoney Tools, including but not limited to text, graphics, logos, and software, is the property of WorkMoney Tools or its content suppliers and is protected by intellectual property laws. You may not reproduce, distribute, or create derivative works without our express permission.',
        'terms.modifications': 'Modifications to Service',
        'terms.modificationsText': 'We reserve the right to modify, suspend, or discontinue any part of the Service at any time without notice. We may also update these Terms of Service from time to time. Continued use of the Service after changes constitutes acceptance of the new terms.',
        'terms.governing': 'Governing Law',
        'terms.governingText': 'These Terms shall be governed by and construed in accordance with the laws of the United States, without regard to its conflict of law provisions.',
        'terms.contactInfo': 'Contact Information',
        'terms.contactInfoText': 'If you have any questions about these Terms of Service, please contact us at',
    },
    zh: {
        // Navigation
        'nav.home': '首页',
        'nav.calculators': '计算器',
        'nav.categories': '分类',
        'nav.about': '关于我们',
        'nav.contact': '联系我们',
        'nav.allTools': '所有工具',
        'nav.search': '搜索计算器...',
        
        // Hero
        'hero.badge': '新工具上线',
        'hero.title1': '智能计算器，助力',
        'hero.title2': '财务未来',
        'hero.subtitle': '使用我们免费、准确且易用的工具做出更明智的决策。从工资税到投资增长，我们为您提供全方位服务。',
        'hero.searchPlaceholder': '搜索计算器... 例如：房贷、税务、利息',
        'hero.trending': '热门：',
        
        // Popular Tools
        'popular.title': '热门计算器',
        'popular.subtitle': '社区最常用的工具',
        
        // Categories Section
        'categories.title': '按类别浏览',
        'categories.subtitle': '找到适合您需求的计算器',
        'categories.viewAll': '查看全部',
        
        // Category Names
        'cat.finance': '财务',
        'cat.business': '商业',
        'cat.loansDebt': '贷款与债务',
        'cat.investment': '投资',
        'cat.health': '健康',
        'cat.math': '数学',
        'cat.geometry': '几何',
        'cat.conversion': '单位换算',
        'cat.everydayLife': '日常生活',
        'cat.biology': '生物',
        'cat.chemistry': '化学',
        'cat.physics': '物理',
        'cat.sports': '运动',
        'cat.statistics': '统计',
        'cat.other': '其他',
        
        // Category Descriptions
        'cat.finance.desc': '工资、税务、投资和退休规划。',
        'cat.business.desc': '投资回报率、利润率、盈亏平衡点等商业计算。',
        'cat.loansDebt.desc': '房贷、车贷和分期还款计算器。',
        'cat.investment.desc': '复利、401k和通货膨胀计算器。',
        'cat.health.desc': 'BMI、基础代谢率、孕期和健身追踪。',
        'cat.math.desc': '代数、几何、统计和矩阵计算。',
        'cat.geometry.desc': '计算面积、体积和建筑需求。',
        'cat.conversion.desc': '长度、重量、体积、温度等单位转换。',
        'cat.everydayLife.desc': '时间、日期、购物和日常工具。',
        'cat.biology.desc': '遗传学、细胞生物学和进化计算器。',
        'cat.chemistry.desc': '摩尔浓度、pH值、元素周期表和化学反应。',
        'cat.physics.desc': '力学、热力学、电学和波动。',
        'cat.sports.desc': '跑步配速、骑行功率和计分板。',
        'cat.statistics.desc': '概率、分布和数据分析。',
        'cat.other.desc': '杂项工具和趣味计算器。',
        
        // Tool Names
        'tool.salaryCalculator': '工资计算器',
        'tool.mortgageCalc': '房贷计算',
        'tool.investmentReturn': '投资回报',
        'tool.roiCalculator': 'ROI计算器',
        'tool.marginCalc': '利润率计算',
        'tool.breakEven': '盈亏平衡',
        'tool.autoLoan': '车贷',
        'tool.amortization': '分期还款',
        'tool.compoundInterest': '复利',
        'tool.401kCalc': '401k计算',
        'tool.inflation': '通货膨胀',
        'tool.bmiCalculator': 'BMI计算器',
        'tool.calorieCalc': '卡路里计算',
        'tool.dueDate': '预产期',
        'tool.percentageCalc': '百分比计算',
        'tool.binaryCalc': '二进制计算',
        'tool.primeNumbers': '质数计算',
        'tool.circleCalc': '圆形计算',
        'tool.triangleCalc': '三角形计算',
        'tool.paintCalculator': '油漆计算器',
        'tool.lengthConverter': '长度换算',
        'tool.weightConverter': '重量换算',
        'tool.currency': '货币换算',
        'tool.ageCalculator': '年龄计算器',
        'tool.dateDifference': '日期差异',
        'tool.tipCalculator': '小费计算器',
        'tool.dnaReplication': 'DNA复制',
        'tool.alleleFrequency': '等位基因频率',
        'tool.molarityCalc': '摩尔浓度',
        'tool.phCalculator': 'pH计算器',
        'tool.velocityCalculator': '速度计算器',
        'tool.paceCalculator': '配速计算器',
        'tool.standardDeviation': '标准差',
        'tool.randomNumberGenerator': '随机数生成器',
        
        // Popular Tools Names & Descriptions
        'popular.paycheck': '工资单计算器',
        'popular.paycheck.desc': '计算扣税后的实际到手工资。',
        'popular.mortgage': '房贷计算器',
        'popular.mortgage.desc': '计算包含税费和保险的月供金额。',
        'popular.bmi': 'BMI计算器',
        'popular.bmi.desc': '根据身高体重计算身体质量指数。',
        'popular.tip': '小费计算器',
        'popular.tip.desc': '计算小费金额并分摊账单。',
        'popular.gpa': 'GPA计算器',
        'popular.gpa.desc': '快速计算您的平均绩点。',
        'popular.age': '年龄计算器',
        'popular.age.desc': '精确计算年龄（年、月、日）。',
        'popular.sleep': '睡眠计算器',
        'popular.sleep.desc': '根据睡眠周期找到最佳起床时间。',
        'popular.password': '密码生成器',
        'popular.password.desc': '即时创建强壮、安全的密码。',
        'popular.compound': '复利计算器',
        'popular.compound.desc': '查看您的投资随时间增长情况。',
        'popular.bodyFat': '体脂计算器',
        'popular.bodyFat.desc': '使用海军方法估算体脂百分比。',
        'popular.homeAfford': '购房能力',
        'popular.homeAfford.desc': '根据收入计算您能负担的房价。',
        'popular.studentLoan': '学生贷款计算器',
        'popular.studentLoan.desc': '规划您的学生贷款还款策略。',
        
        // Popular Tool Categories
        'popular.cat.salary': '工资',
        'popular.cat.loans': '贷款',
        'popular.cat.health': '健康',
        'popular.cat.everyday': '日常',
        'popular.cat.education': '教育',
        'popular.cat.tools': '工具',
        'popular.cat.security': '安全',
        'popular.cat.investment': '投资',
        'popular.cat.fitness': '健身',
        'popular.cat.finance': '财务',
        
        // Calculator Page
        'calc.calculate': '计算',
        'calc.reset': '重置',
        'calc.result': '结果',
        'calc.howItWorks': '工作原理',
        'calc.formula': '公式',
        'calc.faq': '常见问题',
        
        // Footer
        'footer.disclaimer': '本网站不提供税务、法律或投资建议。所有计算仅为估算，仅供参考。',
        'footer.copyright': '版权所有',
        'footer.calculators': '计算器',
        'footer.company': '公司',
        'footer.salaryTax': '工资与税务',
        'footer.loansDebt': '贷款与债务',
        'footer.investment': '投资',
        'footer.aboutUs': '关于我们',
        'footer.privacy': '隐私政策',
        'footer.terms': '服务条款',
        
        // Tags
        'tag.tax': '税务',
        'tag.mortgage': '房贷',
        'tag.loan': '贷款',
        'tag.debt': '债务',
        'tag.bmi': 'BMI',
        'tag.calorie': '卡路里',
        'tag.percentage': '百分比',
        'tag.binary': '二进制',
        'tag.circle': '圆形',
        'tag.triangle': '三角形',
        
        // About Page
        'about.title': '关于 WorkMoney Tools',
        'about.subtitle': '我们提供免费、准确、易用的在线计算器，帮助您做出更好的财务决策，解决日常问题。',
        'about.mission': '我们的使命',
        'about.missionText': '我们的使命是让每个人都能使用财务和数学工具。我们相信每个人都应该能够使用准确的计算器，而无需昂贵的软件或专业服务。',
        'about.whyChoose': '为什么选择我们？',
        'about.fast': '快速准确',
        'about.fastDesc': '我们的计算器使用经过验证的公式和算法，提供即时、准确的结果。',
        'about.userFriendly': '用户友好',
        'about.userFriendlyDesc': '简洁直观的界面，让复杂的计算变得简单易懂。',
        'about.privacy': '隐私优先',
        'about.privacyDesc': '所有计算都在您的浏览器中进行，我们绝不存储您的个人数据。',
        'about.calculators': '计算器',
        'about.categories': '分类',
        'about.free': '免费',
        'about.dataCollected': '数据收集',
        'about.disclaimer': '免责声明',
        'about.disclaimerText': '本网站提供的计算器仅供参考。它们不构成税务、法律、财务或投资建议。',
        
        // All Tools Page
        'allTools.title': '所有计算器',
        'allTools.subtitle': '浏览我们的完整免费计算器集合',
        'allTools.searchPlaceholder': '搜索计算器...',
        'allTools.allCategories': '所有分类',
        'allTools.showing': '显示',
        'allTools.calculator': '个计算器',
        'allTools.calculators': '个计算器',
        'allTools.in': '在',
        'allTools.matching': '匹配',
        'allTools.noFound': '未找到计算器',
        'allTools.tryAdjusting': '请尝试调整搜索或筛选条件',
        'allTools.clearFilters': '清除筛选',
        'allTools.browseByCategory': '按类别浏览',
        'allTools.tools': '个工具',
        
        // Contact Page
        'contact.title': '联系我们',
        'contact.subtitle': '有问题、建议或发现错误？我们很乐意听取您的意见！',
        'contact.feedback': '反馈',
        'contact.feedbackDesc': '帮助我们改进！分享您对新计算器或功能的想法。',
        'contact.email': '电子邮件',
        'contact.yourName': '您的姓名',
        'contact.emailAddress': '电子邮件地址',
        'contact.subject': '主题',
        'contact.selectSubject': '选择主题',
        'contact.generalFeedback': '一般反馈',
        'contact.reportBug': '报告错误',
        'contact.featureRequest': '功能请求',
        'contact.question': '问题',
        'contact.other': '其他',
        'contact.message': '消息',
        'contact.messagePlaceholder': '告诉我们您的想法...',
        'contact.sendMessage': '发送消息',
        'contact.messageSent': '消息已发送！',
        'contact.thankYou': '感谢您的联系。我们会尽快回复您。',
        'contact.sendAnother': '发送另一条消息',
        
        // 404 Page
        'notFound.title': '页面未找到',
        'notFound.message': '抱歉！您要找的页面不存在或已被移动。让我们帮您回到正轨。',
        'notFound.goHome': '返回首页',
        'notFound.browseCalc': '浏览计算器',
        'notFound.popularCalc': '热门计算器',
        
        // Breadcrumbs
        'breadcrumb.home': '首页',
        
        // Related Categories
        'related.title': '相关分类',
        
        // Common
        'common.loading': '加载中...',
        'common.error': '错误',
        'common.noResults': '未找到结果',
        'common.readMore': '阅读更多',
        'common.showLess': '收起',
        
        // SEO Meta
        'seo.home.title': '80+ 免费在线计算器 - 财务、健康、数学等',
        'seo.home.description': '访问80多个免费、准确的在线计算器，包括工资、房贷、BMI、小费、GPA、学生贷款等。数百万用户信赖的日常财务和数学智能工具。',
        'seo.home.keywords': '在线计算器, 免费计算器, 工资计算器, 房贷计算器, BMI计算器, 小费计算器, GPA计算器, 学生贷款计算器, 财务工具',
        
        // Privacy Page
        'privacy.title': '隐私政策',
        'privacy.lastUpdated': '最后更新：2024年12月',
        'privacy.summary': '我们尊重您的隐私。所有计算都在您的浏览器中进行 - 我们不存储您的个人数据。我们使用分析工具来改进服务，并可能显示广告以保持工具免费。',
        'privacy.infoCollect': '我们收集的信息',
        'privacy.calcData': '计算器数据',
        'privacy.calcDataDesc': '所有计算都在您的浏览器本地执行。我们不收集、存储或传输您在计算器中输入的任何数字或信息。',
        'privacy.analyticsData': '分析数据',
        'privacy.analyticsDataDesc': '我们使用 Vercel Analytics 收集匿名使用数据，例如：',
        'privacy.pagesVisited': '访问的页面',
        'privacy.browserType': '浏览器类型和版本',
        'privacy.deviceType': '设备类型（移动设备/桌面设备）',
        'privacy.geoLocation': '一般地理位置（国家级别）',
        'privacy.howUse': '我们如何使用信息',
        'privacy.howUseDesc': '我们使用分析数据来：',
        'privacy.improveCalc': '改进我们的计算器和用户体验',
        'privacy.popularTools': '了解哪些工具最受欢迎',
        'privacy.fixIssues': '识别和修复技术问题',
        'privacy.newFeatures': '做出关于新功能的明智决策',
        'privacy.cookies': 'Cookie 和跟踪',
        'privacy.cookiesDesc1': '我们使用网站正常运行所必需的最少 Cookie。Google AdSense 等第三方服务可能使用 Cookie 来提供相关广告。',
        'privacy.cookiesDesc2': '您可以通过浏览器设置控制 Cookie 偏好。',
        'privacy.thirdParty': '第三方服务',
        'privacy.thirdPartyDesc': '我们使用以下第三方服务：',
        'privacy.vercel': 'Vercel',
        'privacy.vercelDesc': '网站托管和分析',
        'privacy.adsense': 'Google AdSense',
        'privacy.adsenseDesc': '广告（帮助保持我们的工具免费）',
        'privacy.thirdPartyNote': '这些服务有自己的隐私政策来管理其数据实践。',
        'privacy.dataSecurity': '数据安全',
        'privacy.dataSecurityDesc': '由于我们不收集个人计算器数据，因此我们这边没有需要保护的内容。您的计算保留在您的浏览器中，永远不会传输到我们的服务器。',
        'privacy.yourRights': '您的权利',
        'privacy.yourRightsDesc': '您有权通过使用广告拦截器或"请勿跟踪"设置等浏览器扩展来选择退出分析跟踪。由于我们不收集个人数据，因此没有可访问、修改或删除的个人信息。',
        'privacy.childrenPrivacy': '儿童隐私',
        'privacy.childrenPrivacyDesc': '我们的网站面向普通受众，不会有意收集 13 岁以下儿童的信息。',
        'privacy.changes': '本政策的变更',
        'privacy.changesDesc': '我们可能会不时更新此隐私政策。我们将通过更新此页面顶部的"最后更新"日期来通知用户任何重大变更。',
        'privacy.contact': '联系我们',
        'privacy.contactDesc': '如果您对此隐私政策有任何疑问，请通过以下方式联系我们',
        
        // Terms Page
        'terms.title': '服务条款',
        'terms.lastUpdated': '最后更新：2024年12月',
        'terms.important': '使用 WorkMoney Tools 即表示您同意这些条款。我们的计算器仅供参考，不应被视为专业的财务、税务、法律或医疗建议。',
        'terms.acceptance': '接受条款',
        'terms.acceptanceDesc': '通过访问和使用 WorkMoney Tools（"服务"），您接受并同意受这些服务条款的约束。如果您不同意这些条款，请不要使用我们的网站。',
        'terms.description': '服务描述',
        'terms.descriptionText': 'WorkMoney Tools 提供免费的在线计算器，用于财务、数学、健康等方面的计算。这些工具旨在帮助用户进行估算和理解概念，但在没有专业咨询的情况下不应用于做出重要决策。',
        'terms.disclaimer': '免责声明',
        'terms.disclaimerText1': '本服务按"原样"和"可用"提供，不提供任何明示或暗示的保证。',
        'terms.disclaimerText2': '我们不保证：',
        'terms.errorFree': '计算器在所有情况下都不会出错或产生准确结果',
        'terms.uninterrupted': '服务将始终不间断或可用',
        'terms.suitability': '使用我们的计算器得出的任何结果都适合任何特定目的',
        'terms.notAdvice': '非专业建议',
        'terms.notAdviceText': '本网站提供的计算器和信息仅用于教育和信息目的。它们不能替代：',
        'terms.taxAdvice': '合格会计师或税务顾问提供的专业税务建议',
        'terms.legalAdvice': '持牌律师提供的法律建议',
        'terms.financialAdvice': '认证财务规划师提供的财务建议',
        'terms.medicalAdvice': '合格医疗保健提供者提供的医疗建议',
        'terms.otherAdvice': '任何其他专业建议',
        'terms.consultPro': '在根据我们工具的计算做出重要决策之前，请始终咨询合格的专业人士。',
        'terms.liability': '责任限制',
        'terms.liabilityText': '在法律允许的最大范围内，WORKMONEY TOOLS 对任何间接、附带、特殊、后果性或惩罚性损害，或任何利润或收入损失（无论是直接还是间接产生的），或因您使用服务而导致的任何数据、使用、商誉或其他无形损失不承担责任。',
        'terms.accuracy': '信息准确性',
        'terms.accuracyText': '虽然我们努力提供准确的计算和最新信息，但我们不保证任何信息或计算的准确性、完整性或及时性。税率、利率和其他数据可能会发生变化。用户有责任在依赖任何信息之前进行验证。',
        'terms.userResp': '用户责任',
        'terms.userRespText': '使用我们的服务即表示您同意：',
        'terms.lawfulUse': '仅将计算器用于合法目的',
        'terms.noDisrupt': '不试图破坏或损坏服务',
        'terms.noAutomation': '不使用自动化系统以超出人类合理产生的请求数量的方式访问服务',
        'terms.verify': '使用其他来源或专业人士验证重要计算',
        'terms.ip': '知识产权',
        'terms.ipText': 'WorkMoney Tools 上的所有内容，包括但不限于文本、图形、徽标和软件，均为 WorkMoney Tools 或其内容供应商的财产，并受知识产权法保护。未经我们明确许可，您不得复制、分发或创建衍生作品。',
        'terms.modifications': '服务修改',
        'terms.modificationsText': '我们保留随时修改、暂停或终止服务任何部分的权利，恕不另行通知。我们也可能不时更新这些服务条款。在更改后继续使用服务即表示接受新条款。',
        'terms.governing': '适用法律',
        'terms.governingText': '本条款应受美国法律管辖和解释，不考虑其法律冲突条款。',
        'terms.contactInfo': '联系信息',
        'terms.contactInfoText': '如果您对这些服务条款有任何疑问，请通过以下方式联系我们',
    },
    es: {
        // Navigation
        'nav.home': 'Inicio',
        'nav.calculators': 'Calculadoras',
        'nav.categories': 'Categorías',
        'nav.about': 'Acerca de',
        'nav.contact': 'Contacto',
        'nav.allTools': 'Todas las Herramientas',
        'nav.search': 'Buscar calculadoras...',
        
        // Hero
        'hero.badge': 'Nuevas Herramientas',
        'hero.title1': 'Calculadoras inteligentes para tu',
        'hero.title2': 'futuro financiero.',
        'hero.subtitle': 'Toma mejores decisiones con nuestras herramientas gratuitas, precisas y fáciles de usar. Desde impuestos salariales hasta crecimiento de inversiones.',
        'hero.searchPlaceholder': 'Buscar calculadoras... ej. hipoteca, impuestos',
        'hero.trending': 'Tendencias:',
        
        // Popular Tools
        'popular.title': 'Calculadoras Populares',
        'popular.subtitle': 'Herramientas más utilizadas por nuestra comunidad',
        
        // Categories Section
        'categories.title': 'Explorar por Categoría',
        'categories.subtitle': 'Encuentra la calculadora adecuada para tus necesidades',
        'categories.viewAll': 'Ver Todo',
        
        // Category Names
        'cat.finance': 'Finanzas',
        'cat.business': 'Negocios',
        'cat.loansDebt': 'Préstamos y Deudas',
        'cat.investment': 'Inversión',
        'cat.health': 'Salud',
        'cat.math': 'Matemáticas',
        'cat.geometry': 'Geometría',
        'cat.conversion': 'Conversión',
        'cat.everydayLife': 'Vida Diaria',
        'cat.biology': 'Biología',
        'cat.chemistry': 'Química',
        'cat.physics': 'Física',
        'cat.sports': 'Deportes',
        'cat.statistics': 'Estadística',
        'cat.other': 'Otros',
        
        // Category Descriptions
        'cat.finance.desc': 'Salario, impuestos, inversiones y planificación de jubilación.',
        'cat.business.desc': 'ROI, margen, punto de equilibrio y calculadoras empresariales.',
        'cat.loansDebt.desc': 'Hipoteca, préstamos de auto y calculadoras de amortización.',
        'cat.investment.desc': 'Interés compuesto, 401k y calculadoras de inflación.',
        'cat.health.desc': 'IMC, TMB, embarazo y rastreadores de fitness.',
        'cat.math.desc': 'Álgebra, geometría, estadística y matrices.',
        'cat.geometry.desc': 'Calcula áreas, volúmenes y necesidades de construcción.',
        'cat.conversion.desc': 'Convierte longitud, peso, volumen, temperatura y más.',
        'cat.everydayLife.desc': 'Tiempo, fecha, compras y utilidades diarias.',
        'cat.biology.desc': 'Calculadoras de genética, biología celular y evolución.',
        'cat.chemistry.desc': 'Molaridad, pH, tabla periódica y reacciones.',
        'cat.physics.desc': 'Mecánica, termodinámica, electricidad y ondas.',
        'cat.sports.desc': 'Ritmo de carrera, potencia de ciclismo y marcadores.',
        'cat.statistics.desc': 'Probabilidad, distribuciones y análisis de datos.',
        'cat.other.desc': 'Herramientas misceláneas y calculadoras divertidas.',
        
        // Tool Names
        'tool.salaryCalculator': 'Calculadora de Salario',
        'tool.mortgageCalc': 'Calc. Hipoteca',
        'tool.investmentReturn': 'Retorno de Inversión',
        'tool.roiCalculator': 'Calculadora ROI',
        'tool.marginCalc': 'Calc. Margen',
        'tool.breakEven': 'Punto de Equilibrio',
        'tool.autoLoan': 'Préstamo Auto',
        'tool.amortization': 'Amortización',
        'tool.compoundInterest': 'Interés Compuesto',
        'tool.401kCalc': 'Calc. 401k',
        'tool.inflation': 'Inflación',
        'tool.bmiCalculator': 'Calculadora IMC',
        'tool.calorieCalc': 'Calc. Calorías',
        'tool.dueDate': 'Fecha de Parto',
        'tool.percentageCalc': 'Calc. Porcentaje',
        'tool.binaryCalc': 'Calc. Binario',
        'tool.primeNumbers': 'Números Primos',
        'tool.circleCalc': 'Calc. Círculo',
        'tool.triangleCalc': 'Calc. Triángulo',
        'tool.paintCalculator': 'Calc. Pintura',
        'tool.lengthConverter': 'Convertidor de Longitud',
        'tool.weightConverter': 'Convertidor de Peso',
        'tool.currency': 'Moneda',
        'tool.ageCalculator': 'Calculadora de Edad',
        'tool.dateDifference': 'Diferencia de Fechas',
        'tool.tipCalculator': 'Calculadora de Propina',
        'tool.dnaReplication': 'Replicación ADN',
        'tool.alleleFrequency': 'Frecuencia Alélica',
        'tool.molarityCalc': 'Calc. Molaridad',
        'tool.phCalculator': 'Calculadora pH',
        'tool.velocityCalculator': 'Calc. Velocidad',
        'tool.paceCalculator': 'Calc. Ritmo',
        'tool.standardDeviation': 'Desviación Estándar',
        'tool.randomNumberGenerator': 'Generador de Números Aleatorios',
        
        // Popular Tools Names & Descriptions
        'popular.paycheck': 'Calculadora de Nómina',
        'popular.paycheck.desc': 'Calcula tu salario neto después de impuestos.',
        'popular.mortgage': 'Calculadora de Hipoteca',
        'popular.mortgage.desc': 'Calcula pagos mensuales con impuestos y seguro.',
        'popular.bmi': 'Calculadora de IMC',
        'popular.bmi.desc': 'Calcula tu Índice de Masa Corporal según altura y peso.',
        'popular.tip': 'Calculadora de Propina',
        'popular.tip.desc': 'Calcula la propina y divide la cuenta entre amigos.',
        'popular.gpa': 'Calculadora GPA',
        'popular.gpa.desc': 'Calcula tu Promedio de Calificaciones al instante.',
        'popular.age': 'Calculadora de Edad',
        'popular.age.desc': 'Calcula la edad exacta en años, meses y días.',
        'popular.sleep': 'Calculadora de Sueño',
        'popular.sleep.desc': 'Encuentra el mejor momento para despertar según los ciclos de sueño.',
        'popular.password': 'Generador de Contraseñas',
        'popular.password.desc': 'Crea contraseñas fuertes y seguras al instante.',
        'popular.compound': 'Interés Compuesto',
        'popular.compound.desc': 'Ve cómo crecen tus inversiones con el tiempo.',
        'popular.bodyFat': 'Calculadora de Grasa Corporal',
        'popular.bodyFat.desc': 'Estima tu porcentaje de grasa corporal con el método Navy.',
        'popular.homeAfford': 'Asequibilidad de Vivienda',
        'popular.homeAfford.desc': '¿Cuánta casa puedes permitirte según tus ingresos?',
        'popular.studentLoan': 'Calculadora de Préstamo Estudiantil',
        'popular.studentLoan.desc': 'Planifica tu estrategia de pago de préstamos estudiantiles.',
        
        // Popular Tool Categories
        'popular.cat.salary': 'Salario',
        'popular.cat.loans': 'Préstamos',
        'popular.cat.health': 'Salud',
        'popular.cat.everyday': 'Diario',
        'popular.cat.education': 'Educación',
        'popular.cat.tools': 'Herramientas',
        'popular.cat.security': 'Seguridad',
        'popular.cat.investment': 'Inversión',
        'popular.cat.fitness': 'Fitness',
        'popular.cat.finance': 'Finanzas',
        
        // Calculator Page
        'calc.calculate': 'Calcular',
        'calc.reset': 'Reiniciar',
        'calc.result': 'Resultado',
        'calc.howItWorks': 'Cómo Funciona',
        'calc.formula': 'Fórmula',
        'calc.faq': 'Preguntas Frecuentes',
        
        // Footer
        'footer.disclaimer': 'Este sitio web no proporciona asesoramiento fiscal, legal o de inversión. Todos los cálculos son estimaciones y solo deben usarse con fines informativos.',
        'footer.copyright': 'Todos los derechos reservados.',
        'footer.calculators': 'Calculadoras',
        'footer.company': 'Empresa',
        'footer.salaryTax': 'Salario e Impuestos',
        'footer.loansDebt': 'Préstamos y Deudas',
        'footer.investment': 'Inversión',
        'footer.aboutUs': 'Sobre Nosotros',
        'footer.privacy': 'Política de Privacidad',
        'footer.terms': 'Términos de Servicio',
        
        // Tags
        'tag.tax': 'Impuestos',
        'tag.mortgage': 'Hipoteca',
        'tag.loan': 'Préstamo',
        'tag.debt': 'Deuda',
        'tag.bmi': 'IMC',
        'tag.calorie': 'Calorías',
        'tag.percentage': 'Porcentaje',
        'tag.binary': 'Binario',
        'tag.circle': 'Círculo',
        'tag.triangle': 'Triángulo',
        
        // About Page
        'about.title': 'Acerca de WorkMoney Tools',
        'about.subtitle': 'Proporcionamos calculadoras en línea gratuitas, precisas y fáciles de usar para ayudarte a tomar mejores decisiones financieras.',
        'about.mission': 'Nuestra Misión',
        'about.missionText': 'Nuestra misión es democratizar el acceso a herramientas financieras y matemáticas. Creemos que todos deberían tener acceso a calculadoras precisas.',
        'about.whyChoose': '¿Por qué Elegirnos?',
        'about.fast': 'Rápido y Preciso',
        'about.fastDesc': 'Nuestras calculadoras usan fórmulas probadas para entregar resultados instantáneos y precisos.',
        'about.userFriendly': 'Fácil de Usar',
        'about.userFriendlyDesc': 'Interfaces limpias e intuitivas que hacen cálculos complejos simples.',
        'about.privacy': 'Privacidad Primero',
        'about.privacyDesc': 'Todos los cálculos ocurren en tu navegador. Nunca almacenamos tus datos personales.',
        'about.calculators': 'Calculadoras',
        'about.categories': 'Categorías',
        'about.free': 'Gratis',
        'about.dataCollected': 'Datos Recopilados',
        'about.disclaimer': 'Descargo',
        'about.disclaimerText': 'Las calculadoras son solo para fines informativos. No constituyen asesoramiento fiscal, legal o de inversión.',
        
        // All Tools Page
        'allTools.title': 'Todas las Calculadoras',
        'allTools.subtitle': 'Explora nuestra colección completa de calculadoras gratuitas',
        'allTools.searchPlaceholder': 'Buscar calculadoras...',
        'allTools.allCategories': 'Todas las Categorías',
        'allTools.showing': 'Mostrando',
        'allTools.calculator': 'calculadora',
        'allTools.calculators': 'calculadoras',
        'allTools.in': 'en',
        'allTools.matching': 'que coinciden con',
        'allTools.noFound': 'No se encontraron calculadoras',
        'allTools.tryAdjusting': 'Intenta ajustar tu búsqueda o filtros',
        'allTools.clearFilters': 'Limpiar Filtros',
        'allTools.browseByCategory': 'Explorar por Categoría',
        'allTools.tools': 'herramientas',
        
        // Contact Page
        'contact.title': 'Contáctanos',
        'contact.subtitle': '¿Tienes una pregunta, sugerencia o encontraste un error? ¡Nos encantaría saber de ti!',
        'contact.feedback': 'Comentarios',
        'contact.feedbackDesc': '¡Ayúdanos a mejorar! Comparte tus ideas para nuevas calculadoras.',
        'contact.email': 'Correo',
        'contact.yourName': 'Tu Nombre',
        'contact.emailAddress': 'Correo Electrónico',
        'contact.subject': 'Asunto',
        'contact.selectSubject': 'Selecciona un asunto',
        'contact.generalFeedback': 'Comentario General',
        'contact.reportBug': 'Reportar Error',
        'contact.featureRequest': 'Solicitar Función',
        'contact.question': 'Pregunta',
        'contact.other': 'Otro',
        'contact.message': 'Mensaje',
        'contact.messagePlaceholder': 'Cuéntanos qué piensas...',
        'contact.sendMessage': 'Enviar Mensaje',
        'contact.messageSent': '¡Mensaje Enviado!',
        'contact.thankYou': 'Gracias por contactarnos. Te responderemos lo antes posible.',
        'contact.sendAnother': 'Enviar Otro Mensaje',
        
        // 404 Page
        'notFound.title': 'Página No Encontrada',
        'notFound.message': '¡Ups! La página que buscas no existe. Vamos a ayudarte a volver.',
        'notFound.goHome': 'Ir a Inicio',
        'notFound.browseCalc': 'Explorar Calculadoras',
        'notFound.popularCalc': 'Calculadoras Populares',
        
        // Breadcrumbs
        'breadcrumb.home': 'Inicio',
        
        // Related Categories
        'related.title': 'Categorías Relacionadas',
        
        // Common
        'common.loading': 'Cargando...',
        'common.error': 'Error',
        'common.noResults': 'No se encontraron resultados',
        'common.readMore': 'Leer Más',
        'common.showLess': 'Mostrar Menos',
        
        // SEO Meta
        'seo.home.title': '80+ Calculadoras Gratis en Línea - Finanzas, Salud, Matemáticas y Más',
        'seo.home.description': 'Accede a más de 80 calculadoras en línea gratuitas y precisas para nómina, hipoteca, IMC, propina, GPA, préstamos estudiantiles y más. Herramientas inteligentes confiables para necesidades financieras y matemáticas diarias.',
        'seo.home.keywords': 'calculadora en línea, calculadora gratis, calculadora de nómina, calculadora de hipoteca, calculadora IMC, calculadora de propina, calculadora GPA, calculadora de préstamos estudiantiles, herramientas financieras',
        
        // Privacy Page
        'privacy.title': 'Política de Privacidad',
        'privacy.lastUpdated': 'Última actualización: Diciembre 2024',
        'privacy.summary': 'Respetamos su privacidad. Todos los cálculos ocurren en su navegador - no almacenamos sus datos personales. Usamos analíticas para mejorar nuestro servicio y podemos mostrar anuncios para mantener nuestras herramientas gratuitas.',
        'privacy.infoCollect': 'Información que Recopilamos',
        'privacy.calcData': 'Datos de Calculadora',
        'privacy.calcDataDesc': 'Todos los cálculos se realizan localmente en su navegador. No recopilamos, almacenamos ni transmitimos ninguno de los números o información que ingrese en nuestras calculadoras.',
        'privacy.analyticsData': 'Datos Analíticos',
        'privacy.analyticsDataDesc': 'Utilizamos Vercel Analytics para recopilar datos de uso anónimos como:',
        'privacy.pagesVisited': 'Páginas visitadas',
        'privacy.browserType': 'Tipo y versión de navegador',
        'privacy.deviceType': 'Tipo de dispositivo (móvil/escritorio)',
        'privacy.geoLocation': 'Ubicación geográfica general (nivel de país)',
        'privacy.howUse': 'Cómo Utilizamos la Información',
        'privacy.howUseDesc': 'Utilizamos datos analíticos para:',
        'privacy.improveCalc': 'Mejorar nuestras calculadoras y experiencia de usuario',
        'privacy.popularTools': 'Entender qué herramientas son más populares',
        'privacy.fixIssues': 'Identificar y solucionar problemas técnicos',
        'privacy.newFeatures': 'Tomar decisiones informadas sobre nuevas funciones',
        'privacy.cookies': 'Cookies y Seguimiento',
        'privacy.cookiesDesc1': 'Utilizamos cookies mínimas necesarias para el funcionamiento del sitio web. Servicios de terceros como Google AdSense pueden usar cookies para ofrecer anuncios relevantes.',
        'privacy.cookiesDesc2': 'Puede controlar las preferencias de cookies a través de la configuración de su navegador.',
        'privacy.thirdParty': 'Servicios de Terceros',
        'privacy.thirdPartyDesc': 'Utilizamos los siguientes servicios de terceros:',
        'privacy.vercel': 'Vercel',
        'privacy.vercelDesc': 'Alojamiento web y analíticas',
        'privacy.adsense': 'Google AdSense',
        'privacy.adsenseDesc': 'Publicidad (ayuda a mantener nuestras herramientas gratuitas)',
        'privacy.thirdPartyNote': 'Estos servicios tienen sus propias políticas de privacidad que rigen sus prácticas de datos.',
        'privacy.dataSecurity': 'Seguridad de Datos',
        'privacy.dataSecurityDesc': 'Como no recopilamos datos personales de calculadora, no hay nada que asegurar de nuestro lado. Sus cálculos permanecen en su navegador y nunca se transmiten a nuestros servidores.',
        'privacy.yourRights': 'Sus Derechos',
        'privacy.yourRightsDesc': 'Tiene derecho a optar por no participar en el seguimiento analítico mediante el uso de extensiones de navegador como bloqueadores de anuncios o configuraciones de "No Rastrear". Como no recopilamos datos personales, no hay información personal para acceder, modificar o eliminar.',
        'privacy.childrenPrivacy': 'Privacidad de Niños',
        'privacy.childrenPrivacyDesc': 'Nuestro sitio web está destinado a audiencias generales y no recopila intencionalmente información de niños menores de 13 años.',
        'privacy.changes': 'Cambios a Esta Política',
        'privacy.changesDesc': 'Podemos actualizar esta política de privacidad de vez en cuando. Notificaremos a los usuarios de cualquier cambio material actualizando la fecha de "Última actualización" en la parte superior de esta página.',
        'privacy.contact': 'Contáctenos',
        'privacy.contactDesc': 'Si tiene preguntas sobre esta política de privacidad, contáctenos en',
        
        // Terms Page
        'terms.title': 'Términos de Servicio',
        'terms.lastUpdated': 'Última actualización: Diciembre 2024',
        'terms.important': 'Al usar WorkMoney Tools, acepta estos términos. Nuestras calculadoras son solo para fines informativos y no deben considerarse asesoramiento financiero, fiscal, legal o médico profesional.',
        'terms.acceptance': 'Aceptación de Términos',
        'terms.acceptanceDesc': 'Al acceder y usar WorkMoney Tools ("el Servicio"), acepta y está de acuerdo en estar sujeto a estos Términos de Servicio. Si no está de acuerdo con estos términos, no use nuestro sitio web.',
        'terms.description': 'Descripción del Servicio',
        'terms.descriptionText': 'WorkMoney Tools proporciona calculadoras en línea gratuitas para cálculos financieros, matemáticos, de salud y otros. Estas herramientas están diseñadas para ayudar a los usuarios a hacer estimaciones y comprender conceptos, pero no deben ser utilizadas para tomar decisiones importantes sin consulta profesional.',
        'terms.disclaimer': 'Descargo de Garantías',
        'terms.disclaimerText1': 'EL SERVICIO SE PROPORCIONA "TAL CUAL" Y "SEGÚN DISPONIBILIDAD" SIN GARANTÍAS DE NINGÚN TIPO, YA SEA EXPRESA O IMPLÍCITA.',
        'terms.disclaimerText2': 'No garantizamos que:',
        'terms.errorFree': 'Las calculadoras estarán libres de errores o producirán resultados precisos en todas las circunstancias',
        'terms.uninterrupted': 'El servicio estará ininterrumpido o disponible en todo momento',
        'terms.suitability': 'Cualquier resultado del uso de nuestras calculadoras sea adecuado para cualquier propósito específico',
        'terms.notAdvice': 'No es Asesoramiento Profesional',
        'terms.notAdviceText': 'Las calculadoras y la información proporcionada en este sitio web son solo para fines educativos e informativos. NO son sustitutos de:',
        'terms.taxAdvice': 'Asesoramiento fiscal profesional de un contador o asesor fiscal calificado',
        'terms.legalAdvice': 'Asesoramiento legal de un abogado con licencia',
        'terms.financialAdvice': 'Asesoramiento financiero de un planificador financiero certificado',
        'terms.medicalAdvice': 'Asesoramiento médico de un proveedor de atención médica calificado',
        'terms.otherAdvice': 'Cualquier otro asesoramiento profesional',
        'terms.consultPro': 'Siempre consulte con profesionales calificados antes de tomar decisiones importantes basadas en cálculos de nuestras herramientas.',
        'terms.liability': 'Limitación de Responsabilidad',
        'terms.liabilityText': 'EN LA MÁXIMA MEDIDA PERMITIDA POR LA LEY, WORKMONEY TOOLS NO SERÁ RESPONSABLE POR DAÑOS INDIRECTOS, INCIDENTALES, ESPECIALES, CONSECUENTES O PUNITIVOS, O CUALQUIER PÉRDIDA DE GANANCIAS O INGRESOS, YA SEA INCURRIDA DIRECTA O INDIRECTAMENTE, O CUALQUIER PÉRDIDA DE DATOS, USO, BUENA VOLUNTAD U OTRAS PÉRDIDAS INTANGIBLES RESULTANTES DE SU USO DEL SERVICIO.',
        'terms.accuracy': 'Precisión de la Información',
        'terms.accuracyText': 'Si bien nos esforzamos por proporcionar cálculos precisos e información actualizada, no garantizamos la precisión, integridad o puntualidad de cualquier información o cálculo. Las tasas impositivas, tasas de interés y otros datos pueden cambiar. Los usuarios son responsables de verificar cualquier información antes de confiar en ella.',
        'terms.userResp': 'Responsabilidades del Usuario',
        'terms.userRespText': 'Al usar nuestro servicio, acepta:',
        'terms.lawfulUse': 'Usar las calculadoras solo para fines legales',
        'terms.noDisrupt': 'No intentar interrumpir o dañar el servicio',
        'terms.noAutomation': 'No usar sistemas automatizados para acceder al servicio de una manera que envíe más solicitudes de las que un humano podría producir razonablemente',
        'terms.verify': 'Verificar cálculos importantes con otras fuentes o profesionales',
        'terms.ip': 'Propiedad Intelectual',
        'terms.ipText': 'Todo el contenido de WorkMoney Tools, incluyendo pero no limitado a texto, gráficos, logotipos y software, es propiedad de WorkMoney Tools o sus proveedores de contenido y está protegido por leyes de propiedad intelectual. No puede reproducir, distribuir o crear obras derivadas sin nuestro permiso expreso.',
        'terms.modifications': 'Modificaciones del Servicio',
        'terms.modificationsText': 'Nos reservamos el derecho de modificar, suspender o discontinuar cualquier parte del Servicio en cualquier momento sin previo aviso. También podemos actualizar estos Términos de Servicio de vez en cuando. El uso continuado del Servicio después de los cambios constituye la aceptación de los nuevos términos.',
        'terms.governing': 'Ley Aplicable',
        'terms.governingText': 'Estos Términos se regirán e interpretarán de acuerdo con las leyes de los Estados Unidos, sin tener en cuenta sus disposiciones sobre conflictos de leyes.',
        'terms.contactInfo': 'Información de Contacto',
        'terms.contactInfoText': 'Si tiene alguna pregunta sobre estos Términos de Servicio, contáctenos en',
    },
    ja: {
        // Navigation
        'nav.home': 'ホーム',
        'nav.calculators': '電卓',
        'nav.categories': 'カテゴリー',
        'nav.about': '会社概要',
        'nav.contact': 'お問い合わせ',
        'nav.allTools': 'すべてのツール',
        'nav.search': '電卓を検索...',
        
        // Hero
        'hero.badge': '新ツール追加',
        'hero.title1': 'あなたの',
        'hero.title2': '財務の未来のためのスマート電卓',
        'hero.subtitle': '無料で正確、使いやすいツールでより良い決断を。給与税から投資成長まで、すべてお任せください。',
        'hero.searchPlaceholder': '電卓を検索... 例：住宅ローン、税金、利息',
        'hero.trending': 'トレンド：',
        
        // Popular Tools
        'popular.title': '人気の電卓',
        'popular.subtitle': 'コミュニティで最も使用されているツール',
        
        // Categories Section
        'categories.title': 'カテゴリで探す',
        'categories.subtitle': 'ニーズに合った電卓を見つけてください',
        'categories.viewAll': 'すべて見る',
        
        // Category Names
        'cat.finance': '財務',
        'cat.business': 'ビジネス',
        'cat.loansDebt': 'ローン・債務',
        'cat.investment': '投資',
        'cat.health': '健康',
        'cat.math': '数学',
        'cat.geometry': '幾何学',
        'cat.conversion': '単位変換',
        'cat.everydayLife': '日常生活',
        'cat.biology': '生物学',
        'cat.chemistry': '化学',
        'cat.physics': '物理学',
        'cat.sports': 'スポーツ',
        'cat.statistics': '統計',
        'cat.other': 'その他',
        
        // Category Descriptions
        'cat.finance.desc': '給与、税金、投資、退職計画。',
        'cat.business.desc': 'ROI、利益率、損益分岐点などのビジネス計算。',
        'cat.loansDebt.desc': '住宅ローン、自動車ローン、返済計画。',
        'cat.investment.desc': '複利、401k、インフレ計算。',
        'cat.health.desc': 'BMI、基礎代謝、妊娠、フィットネス追跡。',
        'cat.math.desc': '代数、幾何学、統計、行列計算。',
        'cat.geometry.desc': '面積、体積、建築ニーズの計算。',
        'cat.conversion.desc': '長さ、重量、体積、温度などの単位変換。',
        'cat.everydayLife.desc': '時間、日付、ショッピング、日常ツール。',
        'cat.biology.desc': '遺伝学、細胞生物学、進化の計算。',
        'cat.chemistry.desc': 'モル濃度、pH、周期表、化学反応。',
        'cat.physics.desc': '力学、熱力学、電気、波動。',
        'cat.sports.desc': 'ランニングペース、サイクリングパワー、スコアボード。',
        'cat.statistics.desc': '確率、分布、データ分析。',
        'cat.other.desc': 'その他のツールと楽しい電卓。',
        
        // Tool Names
        'tool.salaryCalculator': '給与計算',
        'tool.mortgageCalc': '住宅ローン計算',
        'tool.investmentReturn': '投資リターン',
        'tool.roiCalculator': 'ROI計算',
        'tool.marginCalc': '利益率計算',
        'tool.breakEven': '損益分岐点',
        'tool.autoLoan': '自動車ローン',
        'tool.amortization': '返済計画',
        'tool.compoundInterest': '複利',
        'tool.401kCalc': '401k計算',
        'tool.inflation': 'インフレ',
        'tool.bmiCalculator': 'BMI計算',
        'tool.calorieCalc': 'カロリー計算',
        'tool.dueDate': '出産予定日',
        'tool.percentageCalc': '割合計算',
        'tool.binaryCalc': '2進数計算',
        'tool.primeNumbers': '素数計算',
        'tool.circleCalc': '円計算',
        'tool.triangleCalc': '三角形計算',
        'tool.paintCalculator': 'ペンキ計算',
        'tool.lengthConverter': '長さ変換',
        'tool.weightConverter': '重量変換',
        'tool.currency': '通貨',
        'tool.ageCalculator': '年齢計算',
        'tool.dateDifference': '日付差計算',
        'tool.tipCalculator': 'チップ計算',
        'tool.dnaReplication': 'DNA複製',
        'tool.alleleFrequency': '対立遺伝子頻度',
        'tool.molarityCalc': 'モル濃度',
        'tool.phCalculator': 'pH計算',
        'tool.velocityCalculator': '速度計算',
        'tool.paceCalculator': 'ペース計算',
        'tool.standardDeviation': '標準偏差',
        'tool.randomNumberGenerator': '乱数生成',
        
        // Popular Tools Names & Descriptions
        'popular.paycheck': '給与計算機',
        'popular.paycheck.desc': '税引き後の手取り給与を計算します。',
        'popular.mortgage': '住宅ローン計算機',
        'popular.mortgage.desc': '税金と保険を含む月々の支払いを計算。',
        'popular.bmi': 'BMI計算機',
        'popular.bmi.desc': '身長と体重からBMIを計算します。',
        'popular.tip': 'チップ計算機',
        'popular.tip.desc': 'チップ金額を計算し、友人と割り勘。',
        'popular.gpa': 'GPA計算機',
        'popular.gpa.desc': 'GPA（成績平均点）を即座に計算。',
        'popular.age': '年齢計算機',
        'popular.age.desc': '年、月、日で正確な年齢を計算。',
        'popular.sleep': '睡眠計算機',
        'popular.sleep.desc': '睡眠サイクルに基づく最適な起床時間を発見。',
        'popular.password': 'パスワード生成',
        'popular.password.desc': '強力で安全なパスワードを即座に作成。',
        'popular.compound': '複利計算機',
        'popular.compound.desc': '投資が時間とともにどう成長するか確認。',
        'popular.bodyFat': '体脂肪計算機',
        'popular.bodyFat.desc': 'ネイビー法で体脂肪率を推定。',
        'popular.homeAfford': '住宅購入能力',
        'popular.homeAfford.desc': '収入に基づいていくらの家を買えるか？',
        'popular.studentLoan': '学生ローン計算機',
        'popular.studentLoan.desc': '学生ローンの返済戦略を計画。',
        
        // Popular Tool Categories
        'popular.cat.salary': '給与',
        'popular.cat.loans': 'ローン',
        'popular.cat.health': '健康',
        'popular.cat.everyday': '日常',
        'popular.cat.education': '教育',
        'popular.cat.tools': 'ツール',
        'popular.cat.security': 'セキュリティ',
        'popular.cat.investment': '投資',
        'popular.cat.fitness': 'フィットネス',
        'popular.cat.finance': '財務',
        
        // Calculator Page
        'calc.calculate': '計算する',
        'calc.reset': 'リセット',
        'calc.result': '結果',
        'calc.howItWorks': '仕組み',
        'calc.formula': '計算式',
        'calc.faq': 'よくある質問',
        
        // Footer
        'footer.disclaimer': 'このウェブサイトは税務、法律、投資のアドバイスを提供するものではありません。すべての計算は推定値であり、情報提供のみを目的としています。',
        'footer.copyright': '無断複写・転載を禁じます。',
        'footer.calculators': '電卓',
        'footer.company': '会社情報',
        'footer.salaryTax': '給与・税金',
        'footer.loansDebt': 'ローン・債務',
        'footer.investment': '投資',
        'footer.aboutUs': '会社概要',
        'footer.privacy': 'プライバシーポリシー',
        'footer.terms': '利用規約',
        
        // Tags
        'tag.tax': '税金',
        'tag.mortgage': '住宅ローン',
        'tag.loan': 'ローン',
        'tag.debt': '債務',
        'tag.bmi': 'BMI',
        'tag.calorie': 'カロリー',
        'tag.percentage': '割合',
        'tag.binary': '2進数',
        'tag.circle': '円',
        'tag.triangle': '三角形',
        
        // About Page
        'about.title': 'WorkMoney Toolsについて',
        'about.subtitle': '無料で正確で使いやすいオンライン計算機を提供し、より良い財務決定を支援します。',
        'about.mission': '私たちの使命',
        'about.missionText': '財務・数学ツールへのアクセスを民主化することが私たちの使命です。',
        'about.whyChoose': '選ばれる理由',
        'about.fast': '高速・正確',
        'about.fastDesc': '実証済みの公式とアルゴリズムで即座に正確な結果を提供します。',
        'about.userFriendly': '使いやすい',
        'about.userFriendlyDesc': 'クリーンで直感的なインターフェースで複雑な計算を簡単に。',
        'about.privacy': 'プライバシー優先',
        'about.privacyDesc': 'すべての計算はブラウザ内で行われます。個人データは保存しません。',
        'about.calculators': '計算機',
        'about.categories': 'カテゴリ',
        'about.free': '無料',
        'about.dataCollected': 'データ収集',
        'about.disclaimer': '免責事項',
        'about.disclaimerText': '本サイトの計算機は情報提供のみを目的としています。税務・法律・投資アドバイスではありません。',
        
        // All Tools Page
        'allTools.title': 'すべての計算機',
        'allTools.subtitle': '無料計算機の完全なコレクションを閲覧',
        'allTools.searchPlaceholder': '計算機を検索...',
        'allTools.allCategories': 'すべてのカテゴリ',
        'allTools.showing': '表示中',
        'allTools.calculator': '件の計算機',
        'allTools.calculators': '件の計算機',
        'allTools.in': '',
        'allTools.matching': '一致',
        'allTools.noFound': '計算機が見つかりません',
        'allTools.tryAdjusting': '検索条件を変更してください',
        'allTools.clearFilters': 'フィルターをクリア',
        'allTools.browseByCategory': 'カテゴリで閲覧',
        'allTools.tools': '件のツール',
        
        // Contact Page
        'contact.title': 'お問い合わせ',
        'contact.subtitle': '質問、提案、バグ報告がありますか？ご連絡お待ちしています！',
        'contact.feedback': 'フィードバック',
        'contact.feedbackDesc': '改善にご協力ください！新しい計算機や機能のアイデアを共有してください。',
        'contact.email': 'メール',
        'contact.yourName': 'お名前',
        'contact.emailAddress': 'メールアドレス',
        'contact.subject': '件名',
        'contact.selectSubject': '件名を選択',
        'contact.generalFeedback': '一般的なフィードバック',
        'contact.reportBug': 'バグ報告',
        'contact.featureRequest': '機能リクエスト',
        'contact.question': '質問',
        'contact.other': 'その他',
        'contact.message': 'メッセージ',
        'contact.messagePlaceholder': 'ご意見をお聞かせください...',
        'contact.sendMessage': 'メッセージを送信',
        'contact.messageSent': '送信完了！',
        'contact.thankYou': 'お問い合わせありがとうございます。できるだけ早くご返信いたします。',
        'contact.sendAnother': '別のメッセージを送信',
        
        // 404 Page
        'notFound.title': 'ページが見つかりません',
        'notFound.message': 'お探しのページは存在しないか、移動された可能性があります。',
        'notFound.goHome': 'ホームへ',
        'notFound.browseCalc': '計算機を閲覧',
        'notFound.popularCalc': '人気の計算機',
        
        // Breadcrumbs
        'breadcrumb.home': 'ホーム',
        
        // Related Categories
        'related.title': '関連カテゴリ',
        
        // Common
        'common.loading': '読み込み中...',
        'common.error': 'エラー',
        'common.noResults': '結果が見つかりません',
        'common.readMore': '続きを読む',
        'common.showLess': '閉じる',
        
        // SEO Meta
        'seo.home.title': '80以上の無料オンライン計算機 - 財務、健康、数学など',
        'seo.home.description': '給与、住宅ローン、BMI、チップ、GPA、学生ローンなど、80以上の無料で正確なオンライン計算機にアクセスできます。日常の財務および数学のニーズに何百万人もの人々が信頼するスマートツール。',
        'seo.home.keywords': 'オンライン計算機, 無料計算機, 給与計算機, 住宅ローン計算機, BMI計算機, チップ計算機, GPA計算機, 学生ローン計算機, 財務ツール',
        
        // Privacy Page
        'privacy.title': 'プライバシーポリシー',
        'privacy.lastUpdated': '最終更新：2024年12月',
        'privacy.summary': 'プライバシーを尊重します。すべての計算はブラウザ内で行われ、個人データは保存しません。サービス向上のため分析を使用し、ツールを無料に保つため広告を表示する場合があります。',
        'privacy.infoCollect': '収集する情報',
        'privacy.calcData': '計算機データ',
        'privacy.calcDataDesc': 'すべての計算はブラウザ内でローカルに実行されます。計算機に入力した数値や情報を収集、保存、送信することはありません。',
        'privacy.analyticsData': '分析データ',
        'privacy.analyticsDataDesc': 'Vercel Analyticsを使用して、次のような匿名の使用データを収集しています：',
        'privacy.pagesVisited': '訪問したページ',
        'privacy.browserType': 'ブラウザの種類とバージョン',
        'privacy.deviceType': 'デバイスの種類（モバイル/デスクトップ）',
        'privacy.geoLocation': '一般的な地理的位置（国レベル）',
        'privacy.howUse': '情報の使用方法',
        'privacy.howUseDesc': '分析データは次の目的で使用されます：',
        'privacy.improveCalc': '計算機とユーザーエクスペリエンスの改善',
        'privacy.popularTools': '最も人気のあるツールの把握',
        'privacy.fixIssues': '技術的な問題の特定と修正',
        'privacy.newFeatures': '新機能に関する情報に基づいた決定',
        'privacy.cookies': 'Cookieと追跡',
        'privacy.cookiesDesc1': 'ウェブサイトの機能に必要な最小限のCookieを使用しています。Google AdSenseなどのサードパーティサービスは、関連する広告を配信するためにCookieを使用する場合があります。',
        'privacy.cookiesDesc2': 'ブラウザの設定からCookieの設定を制御できます。',
        'privacy.thirdParty': 'サードパーティサービス',
        'privacy.thirdPartyDesc': '次のサードパーティサービスを使用しています：',
        'privacy.vercel': 'Vercel',
        'privacy.vercelDesc': 'ウェブサイトのホスティングと分析',
        'privacy.adsense': 'Google AdSense',
        'privacy.adsenseDesc': '広告（ツールを無料で提供するため）',
        'privacy.thirdPartyNote': 'これらのサービスには、データの取り扱いを規定する独自のプライバシーポリシーがあります。',
        'privacy.dataSecurity': 'データセキュリティ',
        'privacy.dataSecurityDesc': '個人の計算機データを収集していないため、当社側で保護するものはありません。計算はブラウザに保存され、サーバーに送信されることはありません。',
        'privacy.yourRights': 'あなたの権利',
        'privacy.yourRightsDesc': '広告ブロッカーや「Do Not Track」設定などのブラウザ拡張機能を使用して、分析トラッキングをオプトアウトする権利があります。個人データを収集していないため、アクセス、変更、削除する個人情報はありません。',
        'privacy.childrenPrivacy': '子供のプライバシー',
        'privacy.childrenPrivacyDesc': '当ウェブサイトは一般的な対象者向けであり、13歳未満の子供から故意に情報を収集することはありません。',
        'privacy.changes': 'このポリシーの変更',
        'privacy.changesDesc': 'このプライバシーポリシーは随時更新される場合があります。重要な変更がある場合は、このページ上部の「最終更新」日付を更新してユーザーに通知します。',
        'privacy.contact': 'お問い合わせ',
        'privacy.contactDesc': 'このプライバシーポリシーに関するご質問は、以下までお問い合わせください',
        
        // Terms Page
        'terms.title': '利用規約',
        'terms.lastUpdated': '最終更新：2024年12月',
        'terms.important': 'WorkMoney Toolsを使用することで、これらの規約に同意したものとみなされます。当社の計算機は情報提供のみを目的としており、専門的な財務、税務、法律、または医療のアドバイスとはみなされません。',
        'terms.acceptance': '規約の承諾',
        'terms.acceptanceDesc': 'WorkMoney Tools（「サービス」）にアクセスして使用することで、この利用規約に拘束されることに同意します。これらの規約に同意しない場合は、当ウェブサイトを使用しないでください。',
        'terms.description': 'サービスの説明',
        'terms.descriptionText': 'WorkMoney Toolsは、財務、数学、健康などの計算のための無料のオンライン計算機を提供します。これらのツールは、ユーザーが概算を作成し、概念を理解するのに役立つように設計されていますが、専門的な相談なしに重要な決定を下すために依存すべきではありません。',
        'terms.disclaimer': '保証の免責事項',
        'terms.disclaimerText1': 'サービスは「現状のまま」および「利用可能な状態」で提供され、明示または黙示を問わずいかなる保証もありません。',
        'terms.disclaimerText2': '次のことは保証されません：',
        'terms.errorFree': '計算機がすべての状況でエラーがなく、正確な結果を生成すること',
        'terms.uninterrupted': 'サービスが中断されず、常に利用可能であること',
        'terms.suitability': '当社の計算機を使用した結果が特定の目的に適していること',
        'terms.notAdvice': '専門的なアドバイスではありません',
        'terms.notAdviceText': '本ウェブサイトで提供される計算機と情報は、教育および情報提供のみを目的としています。これらは次のものの代替ではありません：',
        'terms.taxAdvice': '資格のある会計士または税務アドバイザーによる専門的な税務アドバイス',
        'terms.legalAdvice': '認可された弁護士による法律アドバイス',
        'terms.financialAdvice': '認定ファイナンシャルプランナーによる財務アドバイス',
        'terms.medicalAdvice': '資格のある医療提供者による医療アドバイス',
        'terms.otherAdvice': 'その他の専門的なアドバイス',
        'terms.consultPro': '当社のツールからの計算に基づいて重要な決定を下す前に、必ず資格のある専門家に相談してください。',
        'terms.liability': '責任の制限',
        'terms.liabilityText': '法律で認められる最大限の範囲において、WORKMONEY TOOLSは、サービスの使用により生じた間接的、偶発的、特別、結果的、または懲罰的損害、または直接的または間接的に発生した利益または収益の損失、データ、使用、営業権、またはその他の無形の損失について責任を負いません。',
        'terms.accuracy': '情報の正確性',
        'terms.accuracyText': '正確な計算と最新の情報を提供するよう努めていますが、情報や計算の正確性、完全性、または適時性については保証しません。税率、金利、その他のデータは変更される可能性があります。ユーザーは、情報に依存する前に検証する責任があります。',
        'terms.userResp': 'ユーザーの責任',
        'terms.userRespText': 'サービスを使用することで、次のことに同意します：',
        'terms.lawfulUse': '計算機を合法的な目的でのみ使用する',
        'terms.noDisrupt': 'サービスを妨害または損傷しようとしない',
        'terms.noAutomation': '人間が合理的に生成できる以上のリクエストを送信する方法で自動化システムを使用してサービスにアクセスしない',
        'terms.verify': '重要な計算を他の情報源または専門家と検証する',
        'terms.ip': '知的財産',
        'terms.ipText': 'WorkMoney Tools上のすべてのコンテンツ（テキスト、グラフィック、ロゴ、ソフトウェアを含むがこれらに限定されない）は、WorkMoney Toolsまたはそのコンテンツサプライヤーの財産であり、知的財産法によって保護されています。明示的な許可なしに、複製、配布、または派生物を作成することはできません。',
        'terms.modifications': 'サービスの変更',
        'terms.modificationsText': '予告なしにサービスの一部を変更、一時停止、または中止する権利を留保します。また、この利用規約を随時更新することがあります。変更後もサービスを継続して使用することは、新しい規約の受諾を構成します。',
        'terms.governing': '準拠法',
        'terms.governingText': 'これらの規約は、法の抵触に関する規定を考慮せずに、米国の法律に準拠し、解釈されるものとします。',
        'terms.contactInfo': '連絡先情報',
        'terms.contactInfoText': 'この利用規約についてご質問がある場合は、以下までお問い合わせください',
    },
    fr: {
        // Navigation
        'nav.home': 'Accueil',
        'nav.calculators': 'Calculatrices',
        'nav.categories': 'Catégories',
        'nav.about': 'À propos',
        'nav.contact': 'Contact',
        'nav.allTools': 'Tous les Outils',
        'nav.search': 'Rechercher des calculatrices...',
        
        // Hero
        'hero.badge': 'Nouveaux Outils',
        'hero.title1': 'Des calculatrices intelligentes pour votre',
        'hero.title2': 'avenir financier.',
        'hero.subtitle': 'Prenez de meilleures décisions avec nos outils gratuits, précis et faciles à utiliser. Des impôts sur les salaires à la croissance des investissements.',
        'hero.searchPlaceholder': 'Rechercher... ex. hypothèque, impôts',
        'hero.trending': 'Tendances :',
        
        // Popular Tools
        'popular.title': 'Calculatrices Populaires',
        'popular.subtitle': 'Outils les plus utilisés par notre communauté',
        
        // Categories Section
        'categories.title': 'Parcourir par Catégorie',
        'categories.subtitle': 'Trouvez la calculatrice adaptée à vos besoins',
        'categories.viewAll': 'Voir Tout',
        
        // Category Names
        'cat.finance': 'Finance',
        'cat.business': 'Entreprise',
        'cat.loansDebt': 'Prêts et Dettes',
        'cat.investment': 'Investissement',
        'cat.health': 'Santé',
        'cat.math': 'Mathématiques',
        'cat.geometry': 'Géométrie',
        'cat.conversion': 'Conversion',
        'cat.everydayLife': 'Vie Quotidienne',
        'cat.biology': 'Biologie',
        'cat.chemistry': 'Chimie',
        'cat.physics': 'Physique',
        'cat.sports': 'Sports',
        'cat.statistics': 'Statistiques',
        'cat.other': 'Autres',
        
        // Category Descriptions
        'cat.finance.desc': 'Salaire, impôts, investissements et planification retraite.',
        'cat.business.desc': 'ROI, marge, point mort et calculatrices entreprise.',
        'cat.loansDebt.desc': 'Hypothèque, prêt auto et calculatrices amortissement.',
        'cat.investment.desc': 'Intérêts composés, 401k et calculatrices inflation.',
        'cat.health.desc': 'IMC, métabolisme, grossesse et suivi fitness.',
        'cat.math.desc': 'Algèbre, géométrie, statistiques et matrices.',
        'cat.geometry.desc': 'Calculer surfaces, volumes et besoins construction.',
        'cat.conversion.desc': 'Convertir longueur, poids, volume, température et plus.',
        'cat.everydayLife.desc': 'Temps, date, shopping et utilitaires quotidiens.',
        'cat.biology.desc': 'Génétique, biologie cellulaire et calculatrices évolution.',
        'cat.chemistry.desc': 'Molarité, pH, tableau périodique et réactions.',
        'cat.physics.desc': 'Mécanique, thermodynamique, électricité et ondes.',
        'cat.sports.desc': 'Allure course, puissance cyclisme et tableaux scores.',
        'cat.statistics.desc': 'Probabilité, distributions et analyse données.',
        'cat.other.desc': 'Outils divers et calculatrices amusantes.',
        
        // Tool Names
        'tool.salaryCalculator': 'Calc. Salaire',
        'tool.mortgageCalc': 'Calc. Hypothèque',
        'tool.investmentReturn': 'Retour Investissement',
        'tool.roiCalculator': 'Calculatrice ROI',
        'tool.marginCalc': 'Calc. Marge',
        'tool.breakEven': 'Point Mort',
        'tool.autoLoan': 'Prêt Auto',
        'tool.amortization': 'Amortissement',
        'tool.compoundInterest': 'Intérêts Composés',
        'tool.401kCalc': 'Calc. 401k',
        'tool.inflation': 'Inflation',
        'tool.bmiCalculator': 'Calc. IMC',
        'tool.calorieCalc': 'Calc. Calories',
        'tool.dueDate': 'Date Accouchement',
        'tool.percentageCalc': 'Calc. Pourcentage',
        'tool.binaryCalc': 'Calc. Binaire',
        'tool.primeNumbers': 'Nombres Premiers',
        'tool.circleCalc': 'Calc. Cercle',
        'tool.triangleCalc': 'Calc. Triangle',
        'tool.paintCalculator': 'Calc. Peinture',
        'tool.lengthConverter': 'Convertisseur Longueur',
        'tool.weightConverter': 'Convertisseur Poids',
        'tool.currency': 'Devise',
        'tool.ageCalculator': 'Calculatrice Âge',
        'tool.dateDifference': 'Différence Dates',
        'tool.tipCalculator': 'Calc. Pourboire',
        'tool.dnaReplication': 'Réplication ADN',
        'tool.alleleFrequency': 'Fréquence Allélique',
        'tool.molarityCalc': 'Calc. Molarité',
        'tool.phCalculator': 'Calculatrice pH',
        'tool.velocityCalculator': 'Calc. Vitesse',
        'tool.paceCalculator': 'Calc. Allure',
        'tool.standardDeviation': 'Écart-type',
        'tool.randomNumberGenerator': 'Générateur Nombres Aléatoires',
        
        // Popular Tools Names & Descriptions
        'popular.paycheck': 'Calculatrice Salaire',
        'popular.paycheck.desc': 'Calculez votre salaire net après impôts.',
        'popular.mortgage': 'Calculatrice Hypothèque',
        'popular.mortgage.desc': 'Calculez les paiements mensuels avec taxes et assurance.',
        'popular.bmi': 'Calculatrice IMC',
        'popular.bmi.desc': 'Calculez votre IMC selon taille et poids.',
        'popular.tip': 'Calculatrice Pourboire',
        'popular.tip.desc': 'Calculez le pourboire et partagez la note entre amis.',
        'popular.gpa': 'Calculatrice GPA',
        'popular.gpa.desc': 'Calculez votre moyenne générale instantanément.',
        'popular.age': 'Calculatrice Âge',
        'popular.age.desc': 'Calculez l\'âge exact en années, mois et jours.',
        'popular.sleep': 'Calculatrice Sommeil',
        'popular.sleep.desc': 'Trouvez le meilleur moment pour se réveiller selon les cycles de sommeil.',
        'popular.password': 'Générateur Mot de Passe',
        'popular.password.desc': 'Créez des mots de passe forts et sécurisés instantanément.',
        'popular.compound': 'Intérêts Composés',
        'popular.compound.desc': 'Voyez comment vos investissements croissent dans le temps.',
        'popular.bodyFat': 'Calculatrice Graisse Corporelle',
        'popular.bodyFat.desc': 'Estimez votre pourcentage de graisse corporelle avec la méthode Navy.',
        'popular.homeAfford': 'Capacité d\'Achat Immobilier',
        'popular.homeAfford.desc': 'Quelle maison pouvez-vous vous permettre selon vos revenus?',
        'popular.studentLoan': 'Calculatrice Prêt Étudiant',
        'popular.studentLoan.desc': 'Planifiez votre stratégie de remboursement de prêt étudiant.',
        
        // Popular Tool Categories
        'popular.cat.salary': 'Salaire',
        'popular.cat.loans': 'Prêts',
        'popular.cat.health': 'Santé',
        'popular.cat.everyday': 'Quotidien',
        'popular.cat.education': 'Éducation',
        'popular.cat.tools': 'Outils',
        'popular.cat.security': 'Sécurité',
        'popular.cat.investment': 'Investissement',
        'popular.cat.fitness': 'Fitness',
        'popular.cat.finance': 'Finance',
        
        // Calculator Page
        'calc.calculate': 'Calculer',
        'calc.reset': 'Réinitialiser',
        'calc.result': 'Résultat',
        'calc.howItWorks': 'Comment ça marche',
        'calc.formula': 'Formule',
        'calc.faq': 'FAQ',
        
        // Footer
        'footer.disclaimer': 'Ce site ne fournit pas de conseils fiscaux, juridiques ou d\'investissement. Tous les calculs sont des estimations à titre informatif uniquement.',
        'footer.copyright': 'Tous droits réservés.',
        'footer.calculators': 'Calculatrices',
        'footer.company': 'Entreprise',
        'footer.salaryTax': 'Salaire et Impôts',
        'footer.loansDebt': 'Prêts et Dettes',
        'footer.investment': 'Investissement',
        'footer.aboutUs': 'À propos',
        'footer.privacy': 'Politique de Confidentialité',
        'footer.terms': 'Conditions d\'Utilisation',
        
        // Tags
        'tag.tax': 'Impôts',
        'tag.mortgage': 'Hypothèque',
        'tag.loan': 'Prêt',
        'tag.debt': 'Dette',
        'tag.bmi': 'IMC',
        'tag.calorie': 'Calories',
        'tag.percentage': 'Pourcentage',
        'tag.binary': 'Binaire',
        'tag.circle': 'Cercle',
        'tag.triangle': 'Triangle',
        
        // About Page
        'about.title': 'À Propos de WorkMoney Tools',
        'about.subtitle': 'Nous fournissons des calculatrices en ligne gratuites, précises et faciles à utiliser pour vous aider à prendre de meilleures décisions financières.',
        'about.mission': 'Notre Mission',
        'about.missionText': 'Notre mission est de démocratiser l\'accès aux outils financiers et mathématiques.',
        'about.whyChoose': 'Pourquoi Nous Choisir?',
        'about.fast': 'Rapide et Précis',
        'about.fastDesc': 'Nos calculatrices utilisent des formules éprouvées pour des résultats instantanés et précis.',
        'about.userFriendly': 'Facile à Utiliser',
        'about.userFriendlyDesc': 'Interfaces propres et intuitives qui simplifient les calculs complexes.',
        'about.privacy': 'Confidentialité d\'Abord',
        'about.privacyDesc': 'Tous les calculs se font dans votre navigateur. Nous ne stockons jamais vos données personnelles.',
        'about.calculators': 'Calculatrices',
        'about.categories': 'Catégories',
        'about.free': 'Gratuit',
        'about.dataCollected': 'Données Collectées',
        'about.disclaimer': 'Avertissement',
        'about.disclaimerText': 'Les calculatrices sont fournies à titre informatif uniquement. Elles ne constituent pas des conseils fiscaux, juridiques ou d\'investissement.',
        
        // All Tools Page
        'allTools.title': 'Toutes les Calculatrices',
        'allTools.subtitle': 'Parcourez notre collection complète de calculatrices gratuites',
        'allTools.searchPlaceholder': 'Rechercher des calculatrices...',
        'allTools.allCategories': 'Toutes les Catégories',
        'allTools.showing': 'Affichage de',
        'allTools.calculator': 'calculatrice',
        'allTools.calculators': 'calculatrices',
        'allTools.in': 'dans',
        'allTools.matching': 'correspondant à',
        'allTools.noFound': 'Aucune calculatrice trouvée',
        'allTools.tryAdjusting': 'Essayez d\'ajuster vos critères de recherche',
        'allTools.clearFilters': 'Effacer les Filtres',
        'allTools.browseByCategory': 'Parcourir par Catégorie',
        'allTools.tools': 'outils',
        
        // Contact Page
        'contact.title': 'Contactez-Nous',
        'contact.subtitle': 'Une question, suggestion ou trouvé un bug? Nous aimerions avoir de vos nouvelles!',
        'contact.feedback': 'Commentaires',
        'contact.feedbackDesc': 'Aidez-nous à nous améliorer! Partagez vos idées de nouvelles calculatrices.',
        'contact.email': 'Email',
        'contact.yourName': 'Votre Nom',
        'contact.emailAddress': 'Adresse Email',
        'contact.subject': 'Sujet',
        'contact.selectSubject': 'Sélectionnez un sujet',
        'contact.generalFeedback': 'Commentaire Général',
        'contact.reportBug': 'Signaler un Bug',
        'contact.featureRequest': 'Demande de Fonctionnalité',
        'contact.question': 'Question',
        'contact.other': 'Autre',
        'contact.message': 'Message',
        'contact.messagePlaceholder': 'Dites-nous ce que vous pensez...',
        'contact.sendMessage': 'Envoyer le Message',
        'contact.messageSent': 'Message Envoyé!',
        'contact.thankYou': 'Merci de nous avoir contactés. Nous vous répondrons dès que possible.',
        'contact.sendAnother': 'Envoyer un Autre Message',
        
        // 404 Page
        'notFound.title': 'Page Non Trouvée',
        'notFound.message': 'Oups! La page que vous cherchez n\'existe pas ou a été déplacée.',
        'notFound.goHome': 'Aller à l\'Accueil',
        'notFound.browseCalc': 'Parcourir les Calculatrices',
        'notFound.popularCalc': 'Calculatrices Populaires',
        
        // Breadcrumbs
        'breadcrumb.home': 'Accueil',
        
        // Related Categories
        'related.title': 'Catégories Connexes',
        
        // Common
        'common.loading': 'Chargement...',
        'common.error': 'Erreur',
        'common.noResults': 'Aucun résultat trouvé',
        'common.readMore': 'Lire Plus',
        'common.showLess': 'Voir Moins',
        
        // SEO Meta
        'seo.home.title': '80+ Calculatrices Gratuites en Ligne - Finance, Santé, Mathématiques et Plus',
        'seo.home.description': 'Accédez à plus de 80 calculatrices en ligne gratuites et précises pour salaire, hypothèque, IMC, pourboire, GPA, prêts étudiants et plus. Outils intelligents de confiance pour les besoins financiers et mathématiques quotidiens.',
        'seo.home.keywords': 'calculatrice en ligne, calculatrice gratuite, calculatrice de salaire, calculatrice hypothécaire, calculatrice IMC, calculatrice de pourboire, calculatrice GPA, calculatrice de prêts étudiants, outils financiers',
        
        // Privacy Page
        'privacy.title': 'Politique de Confidentialité',
        'privacy.lastUpdated': 'Dernière mise à jour : Décembre 2024',
        'privacy.summary': 'Nous respectons votre vie privée. Tous les calculs se font dans votre navigateur - nous ne stockons pas vos données personnelles. Nous utilisons des analyses pour améliorer notre service et pouvons afficher des publicités pour garder nos outils gratuits.',
        'privacy.infoCollect': 'Informations que Nous Collectons',
        'privacy.calcData': 'Données de Calculatrice',
        'privacy.calcDataDesc': 'Tous les calculs sont effectués localement dans votre navigateur. Nous ne collectons, stockons ni transmettons aucun des nombres ou informations que vous entrez dans nos calculatrices.',
        'privacy.analyticsData': 'Données Analytiques',
        'privacy.analyticsDataDesc': 'Nous utilisons Vercel Analytics pour collecter des données d\'utilisation anonymes telles que :',
        'privacy.pagesVisited': 'Pages visitées',
        'privacy.browserType': 'Type et version du navigateur',
        'privacy.deviceType': 'Type d\'appareil (mobile/ordinateur)',
        'privacy.geoLocation': 'Localisation géographique générale (niveau pays)',
        'privacy.howUse': 'Comment Nous Utilisons les Informations',
        'privacy.howUseDesc': 'Nous utilisons les données analytiques pour :',
        'privacy.improveCalc': 'Améliorer nos calculatrices et l\'expérience utilisateur',
        'privacy.popularTools': 'Comprendre quels outils sont les plus populaires',
        'privacy.fixIssues': 'Identifier et résoudre les problèmes techniques',
        'privacy.newFeatures': 'Prendre des décisions éclairées sur les nouvelles fonctionnalités',
        'privacy.cookies': 'Cookies et Suivi',
        'privacy.cookiesDesc1': 'Nous utilisons un minimum de cookies nécessaires au fonctionnement du site web. Des services tiers comme Google AdSense peuvent utiliser des cookies pour diffuser des publicités pertinentes.',
        'privacy.cookiesDesc2': 'Vous pouvez contrôler les préférences de cookies via les paramètres de votre navigateur.',
        'privacy.thirdParty': 'Services Tiers',
        'privacy.thirdPartyDesc': 'Nous utilisons les services tiers suivants :',
        'privacy.vercel': 'Vercel',
        'privacy.vercelDesc': 'Hébergement web et analyses',
        'privacy.adsense': 'Google AdSense',
        'privacy.adsenseDesc': 'Publicité (aide à garder nos outils gratuits)',
        'privacy.thirdPartyNote': 'Ces services ont leurs propres politiques de confidentialité régissant leurs pratiques en matière de données.',
        'privacy.dataSecurity': 'Sécurité des Données',
        'privacy.dataSecurityDesc': 'Puisque nous ne collectons pas de données personnelles de calculatrice, il n\'y a rien à sécuriser de notre côté. Vos calculs restent dans votre navigateur et ne sont jamais transmis à nos serveurs.',
        'privacy.yourRights': 'Vos Droits',
        'privacy.yourRightsDesc': 'Vous avez le droit de refuser le suivi analytique en utilisant des extensions de navigateur comme des bloqueurs de publicités ou les paramètres "Do Not Track". Puisque nous ne collectons pas de données personnelles, il n\'y a aucune information personnelle à accéder, modifier ou supprimer.',
        'privacy.childrenPrivacy': 'Confidentialité des Enfants',
        'privacy.childrenPrivacyDesc': 'Notre site web est destiné au grand public et ne collecte pas sciemment d\'informations auprès d\'enfants de moins de 13 ans.',
        'privacy.changes': 'Modifications de Cette Politique',
        'privacy.changesDesc': 'Nous pouvons mettre à jour cette politique de confidentialité de temps en temps. Nous informerons les utilisateurs de tout changement important en mettant à jour la date "Dernière mise à jour" en haut de cette page.',
        'privacy.contact': 'Nous Contacter',
        'privacy.contactDesc': 'Si vous avez des questions sur cette politique de confidentialité, veuillez nous contacter à',
        
        // Terms Page
        'terms.title': 'Conditions d\'Utilisation',
        'terms.lastUpdated': 'Dernière mise à jour : Décembre 2024',
        'terms.important': 'En utilisant WorkMoney Tools, vous acceptez ces conditions. Nos calculatrices sont à titre informatif uniquement et ne doivent pas être considérées comme des conseils professionnels financiers, fiscaux, juridiques ou médicaux.',
        'terms.acceptance': 'Acceptation des Conditions',
        'terms.acceptanceDesc': 'En accédant et en utilisant WorkMoney Tools ("le Service"), vous acceptez et convenez d\'être lié par ces Conditions d\'Utilisation. Si vous n\'acceptez pas ces conditions, veuillez ne pas utiliser notre site web.',
        'terms.description': 'Description du Service',
        'terms.descriptionText': 'WorkMoney Tools fournit des calculatrices en ligne gratuites pour les calculs financiers, mathématiques, de santé et autres. Ces outils sont conçus pour aider les utilisateurs à faire des estimations et à comprendre des concepts, mais ne doivent pas être utilisés pour prendre des décisions importantes sans consultation professionnelle.',
        'terms.disclaimer': 'Avertissement de Garanties',
        'terms.disclaimerText1': 'LE SERVICE EST FOURNI "TEL QUEL" ET "TEL QUE DISPONIBLE" SANS GARANTIES D\'AUCUNE SORTE, EXPLICITES OU IMPLICITES.',
        'terms.disclaimerText2': 'Nous ne garantissons pas que :',
        'terms.errorFree': 'Les calculatrices seront sans erreur ou produiront des résultats précis dans toutes les circonstances',
        'terms.uninterrupted': 'Le service sera ininterrompu ou disponible à tout moment',
        'terms.suitability': 'Les résultats de l\'utilisation de nos calculatrices sont adaptés à un usage spécifique',
        'terms.notAdvice': 'Pas de Conseil Professionnel',
        'terms.notAdviceText': 'Les calculatrices et les informations fournies sur ce site web sont à des fins éducatives et informatives uniquement. Elles ne sont PAS des substituts à :',
        'terms.taxAdvice': 'Conseil fiscal professionnel d\'un comptable ou conseiller fiscal qualifié',
        'terms.legalAdvice': 'Conseil juridique d\'un avocat agréé',
        'terms.financialAdvice': 'Conseil financier d\'un planificateur financier certifié',
        'terms.medicalAdvice': 'Conseil médical d\'un professionnel de santé qualifié',
        'terms.otherAdvice': 'Tout autre conseil professionnel',
        'terms.consultPro': 'Consultez toujours des professionnels qualifiés avant de prendre des décisions importantes basées sur les calculs de nos outils.',
        'terms.liability': 'Limitation de Responsabilité',
        'terms.liabilityText': 'DANS LA MESURE MAXIMALE AUTORISÉE PAR LA LOI, WORKMONEY TOOLS NE SERA PAS RESPONSABLE DES DOMMAGES INDIRECTS, ACCESSOIRES, SPÉCIAUX, CONSÉCUTIFS OU PUNITIFS, OU DE TOUTE PERTE DE PROFITS OU DE REVENUS, DIRECTE OU INDIRECTE, OU DE TOUTE PERTE DE DONNÉES, D\'UTILISATION, DE CLIENTÈLE OU D\'AUTRES PERTES INTANGIBLES RÉSULTANT DE VOTRE UTILISATION DU SERVICE.',
        'terms.accuracy': 'Précision des Informations',
        'terms.accuracyText': 'Bien que nous nous efforcions de fournir des calculs précis et des informations à jour, nous ne garantissons pas l\'exactitude, l\'exhaustivité ou l\'actualité de toute information ou calcul. Les taux d\'imposition, les taux d\'intérêt et autres données peuvent changer. Les utilisateurs sont responsables de vérifier toute information avant de s\'y fier.',
        'terms.userResp': 'Responsabilités de l\'Utilisateur',
        'terms.userRespText': 'En utilisant notre service, vous acceptez de :',
        'terms.lawfulUse': 'Utiliser les calculatrices uniquement à des fins légales',
        'terms.noDisrupt': 'Ne pas tenter de perturber ou d\'endommager le service',
        'terms.noAutomation': 'Ne pas utiliser de systèmes automatisés pour accéder au service d\'une manière qui envoie plus de requêtes qu\'un humain ne pourrait raisonnablement produire',
        'terms.verify': 'Vérifier les calculs importants avec d\'autres sources ou professionnels',
        'terms.ip': 'Propriété Intellectuelle',
        'terms.ipText': 'Tout le contenu de WorkMoney Tools, y compris mais sans s\'y limiter le texte, les graphiques, les logos et les logiciels, est la propriété de WorkMoney Tools ou de ses fournisseurs de contenu et est protégé par les lois sur la propriété intellectuelle. Vous ne pouvez pas reproduire, distribuer ou créer des œuvres dérivées sans notre permission expresse.',
        'terms.modifications': 'Modifications du Service',
        'terms.modificationsText': 'Nous nous réservons le droit de modifier, suspendre ou interrompre toute partie du Service à tout moment sans préavis. Nous pouvons également mettre à jour ces Conditions d\'Utilisation de temps à autre. L\'utilisation continue du Service après les modifications constitue l\'acceptation des nouvelles conditions.',
        'terms.governing': 'Loi Applicable',
        'terms.governingText': 'Ces Conditions seront régies et interprétées conformément aux lois des États-Unis, sans égard à ses dispositions en matière de conflits de lois.',
        'terms.contactInfo': 'Informations de Contact',
        'terms.contactInfoText': 'Si vous avez des questions sur ces Conditions d\'Utilisation, veuillez nous contacter à',
    },
};

export const languageNames: Record<Language, string> = {
    en: 'English',
    zh: '中文',
    es: 'Español',
    ja: '日本語',
    fr: 'Français',
};

export const languageFlags: Record<Language, string> = {
    en: '🇺🇸',
    zh: '🇨🇳',
    es: '🇪🇸',
    ja: '🇯🇵',
    fr: '🇫🇷',
};

interface LanguageProviderProps {
    children: ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
    const [language, setLanguageState] = useState<Language>(() => {
        if (typeof window === 'undefined') return 'en';
        const saved = localStorage.getItem('language') as Language;
        if (saved && translations[saved]) return saved;
        
        const browserLang = navigator.language.split('-')[0];
        if (browserLang === 'zh') return 'zh';
        if (browserLang === 'es') return 'es';
        if (browserLang === 'ja') return 'ja';
        if (browserLang === 'fr') return 'fr';
        return 'en';
    });

    const setLanguage = (lang: Language) => {
        setLanguageState(lang);
        localStorage.setItem('language', lang);
        document.documentElement.lang = lang;
    };

    useEffect(() => {
        document.documentElement.lang = language;
    }, [language]);

    const t = (key: string): string => {
        return translations[language][key] || translations['en'][key] || key;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = (): LanguageContextType => {
    const context = useContext(LanguageContext);
    if (!context) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
};
